// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addon.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddon = `-- name: CreateAddon :one
INSERT INTO mst_addon (
    addon_uuid, name, category, addon_limit, price, status, icon_svg, icon_color
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING addon_uuid, name, category, addon_limit, price, status, icon_svg, icon_color, created_at, updated_at, is_deleted
`

type CreateAddonParams struct {
	AddonUuid  pgtype.UUID `json:"addon_uuid"`
	Name       string      `json:"name"`
	Category   string      `json:"category"`
	AddonLimit string      `json:"addon_limit"`
	Price      string      `json:"price"`
	Status     string      `json:"status"`
	IconSvg    pgtype.Text `json:"icon_svg"`
	IconColor  pgtype.Text `json:"icon_color"`
}

func (q *Queries) CreateAddon(ctx context.Context, arg CreateAddonParams) (MstAddon, error) {
	row := q.db.QueryRow(ctx, createAddon,
		arg.AddonUuid,
		arg.Name,
		arg.Category,
		arg.AddonLimit,
		arg.Price,
		arg.Status,
		arg.IconSvg,
		arg.IconColor,
	)
	var i MstAddon
	err := row.Scan(
		&i.AddonUuid,
		&i.Name,
		&i.Category,
		&i.AddonLimit,
		&i.Price,
		&i.Status,
		&i.IconSvg,
		&i.IconColor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const deleteAddon = `-- name: DeleteAddon :exec
UPDATE mst_addon
SET is_deleted = true, updated_at = now()
WHERE addon_uuid = $1
`

func (q *Queries) DeleteAddon(ctx context.Context, addonUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAddon, addonUuid)
	return err
}

const getAddon = `-- name: GetAddon :one
SELECT addon_uuid, name, category, addon_limit, price, status, icon_svg, icon_color, created_at, updated_at, is_deleted FROM mst_addon
WHERE addon_uuid = $1 AND is_deleted = false
`

func (q *Queries) GetAddon(ctx context.Context, addonUuid pgtype.UUID) (MstAddon, error) {
	row := q.db.QueryRow(ctx, getAddon, addonUuid)
	var i MstAddon
	err := row.Scan(
		&i.AddonUuid,
		&i.Name,
		&i.Category,
		&i.AddonLimit,
		&i.Price,
		&i.Status,
		&i.IconSvg,
		&i.IconColor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const listAddons = `-- name: ListAddons :many
SELECT addon_uuid, name, category, addon_limit, price, status, icon_svg, icon_color, created_at, updated_at, is_deleted FROM mst_addon
WHERE is_deleted = false
ORDER BY created_at DESC
`

func (q *Queries) ListAddons(ctx context.Context) ([]MstAddon, error) {
	rows, err := q.db.Query(ctx, listAddons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MstAddon
	for rows.Next() {
		var i MstAddon
		if err := rows.Scan(
			&i.AddonUuid,
			&i.Name,
			&i.Category,
			&i.AddonLimit,
			&i.Price,
			&i.Status,
			&i.IconSvg,
			&i.IconColor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddon = `-- name: UpdateAddon :one
UPDATE mst_addon
SET
    name = coalesce($1, name),
    category = coalesce($2, category),
    addon_limit = coalesce($3, addon_limit),
    price = coalesce($4, price),
    status = coalesce($5, status),
    icon_svg = coalesce($6, icon_svg),
    icon_color = coalesce($7, icon_color),
    updated_at = now()
WHERE addon_uuid = $8 AND is_deleted = false
RETURNING addon_uuid, name, category, addon_limit, price, status, icon_svg, icon_color, created_at, updated_at, is_deleted
`

type UpdateAddonParams struct {
	Name       pgtype.Text `json:"name"`
	Category   pgtype.Text `json:"category"`
	AddonLimit pgtype.Text `json:"addon_limit"`
	Price      pgtype.Text `json:"price"`
	Status     pgtype.Text `json:"status"`
	IconSvg    pgtype.Text `json:"icon_svg"`
	IconColor  pgtype.Text `json:"icon_color"`
	AddonUuid  pgtype.UUID `json:"addon_uuid"`
}

func (q *Queries) UpdateAddon(ctx context.Context, arg UpdateAddonParams) (MstAddon, error) {
	row := q.db.QueryRow(ctx, updateAddon,
		arg.Name,
		arg.Category,
		arg.AddonLimit,
		arg.Price,
		arg.Status,
		arg.IconSvg,
		arg.IconColor,
		arg.AddonUuid,
	)
	var i MstAddon
	err := row.Scan(
		&i.AddonUuid,
		&i.Name,
		&i.Category,
		&i.AddonLimit,
		&i.Price,
		&i.Status,
		&i.IconSvg,
		&i.IconColor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
