// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminAuth = `-- name: CreateAdminAuth :exec
INSERT INTO user_auth (
    user_auth_uuid, tenant_uuid, user_uuid, login_id, password_hash,
    created_at
) VALUES (
    $1, $2, $3, $4, $5,
    NOW()
)
`

type CreateAdminAuthParams struct {
	UserAuthUuid pgtype.UUID `json:"user_auth_uuid"`
	TenantUuid   pgtype.UUID `json:"tenant_uuid"`
	UserUuid     pgtype.UUID `json:"user_uuid"`
	LoginID      string      `json:"login_id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) CreateAdminAuth(ctx context.Context, arg CreateAdminAuthParams) error {
	_, err := q.db.Exec(ctx, createAdminAuth,
		arg.UserAuthUuid,
		arg.TenantUuid,
		arg.UserUuid,
		arg.LoginID,
		arg.PasswordHash,
	)
	return err
}

const createAdminTenant = `-- name: CreateAdminTenant :exec
INSERT INTO user_tenant (
    user_tenant_uuid, tenant_uuid, user_uuid, employee_code, is_default_tenant,
    created_at
) VALUES (
    $1, $2, $3, $4, true,
    NOW()
)
`

type CreateAdminTenantParams struct {
	UserTenantUuid pgtype.UUID `json:"user_tenant_uuid"`
	TenantUuid     pgtype.UUID `json:"tenant_uuid"`
	UserUuid       pgtype.UUID `json:"user_uuid"`
	EmployeeCode   pgtype.Text `json:"employee_code"`
}

func (q *Queries) CreateAdminTenant(ctx context.Context, arg CreateAdminTenantParams) error {
	_, err := q.db.Exec(ctx, createAdminTenant,
		arg.UserTenantUuid,
		arg.TenantUuid,
		arg.UserUuid,
		arg.EmployeeCode,
	)
	return err
}

const createAdminUser = `-- name: CreateAdminUser :exec
INSERT INTO "user" (
    user_uuid, first_name, last_name, email_address, user_status_universal_uuid,
    created_at, created_by_user_uuid
) VALUES (
    $1, $2, $3, $4, $5,
    NOW(), $6
)
`

type CreateAdminUserParams struct {
	UserUuid                pgtype.UUID `json:"user_uuid"`
	FirstName               string      `json:"first_name"`
	LastName                pgtype.Text `json:"last_name"`
	EmailAddress            pgtype.Text `json:"email_address"`
	UserStatusUniversalUuid pgtype.UUID `json:"user_status_universal_uuid"`
	CreatedByUserUuid       pgtype.UUID `json:"created_by_user_uuid"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error {
	_, err := q.db.Exec(ctx, createAdminUser,
		arg.UserUuid,
		arg.FirstName,
		arg.LastName,
		arg.EmailAddress,
		arg.UserStatusUniversalUuid,
		arg.CreatedByUserUuid,
	)
	return err
}

const createAdminWorkspace = `-- name: CreateAdminWorkspace :exec
INSERT INTO user_workspace (
    user_workspace_uuid, tenant_uuid, user_tenant_uuid, workspace_uuid, role_uuid,
    is_default_workspace, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    true, NOW()
)
`

type CreateAdminWorkspaceParams struct {
	UserWorkspaceUuid pgtype.UUID `json:"user_workspace_uuid"`
	TenantUuid        pgtype.UUID `json:"tenant_uuid"`
	UserTenantUuid    pgtype.UUID `json:"user_tenant_uuid"`
	WorkspaceUuid     pgtype.UUID `json:"workspace_uuid"`
	RoleUuid          pgtype.UUID `json:"role_uuid"`
}

func (q *Queries) CreateAdminWorkspace(ctx context.Context, arg CreateAdminWorkspaceParams) error {
	_, err := q.db.Exec(ctx, createAdminWorkspace,
		arg.UserWorkspaceUuid,
		arg.TenantUuid,
		arg.UserTenantUuid,
		arg.WorkspaceUuid,
		arg.RoleUuid,
	)
	return err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
UPDATE "user"
SET 
    is_deleted = true,
    updated_at = NOW(),
    updated_by_user_uuid = $2
WHERE user_uuid = $1
`

type DeleteAdminParams struct {
	UserUuid          pgtype.UUID `json:"user_uuid"`
	UpdatedByUserUuid pgtype.UUID `json:"updated_by_user_uuid"`
}

func (q *Queries) DeleteAdmin(ctx context.Context, arg DeleteAdminParams) error {
	_, err := q.db.Exec(ctx, deleteAdmin, arg.UserUuid, arg.UpdatedByUserUuid)
	return err
}

const getAdmin = `-- name: GetAdmin :one
SELECT 
    u.user_uuid,
    u.first_name,
    u.last_name,
    ua.login_id AS username,
    u.email_address,
    r.role_name AS role,
    r.role_uuid,
    u_status.value_name AS status,
    u.user_status_universal_uuid AS status_uuid,
    ua.is_mobile_verified AS mfa_enabled,
    ua.last_login_at
FROM "user" u
JOIN user_auth ua ON u.user_uuid = ua.user_uuid
JOIN user_tenant ut ON u.user_uuid = ut.user_uuid
JOIN tenant t ON ut.tenant_uuid = t.tenant_uuid
LEFT JOIN user_workspace uw ON ut.user_tenant_uuid = uw.user_tenant_uuid
LEFT JOIN role r ON uw.role_uuid = r.role_uuid
LEFT JOIN mst_universal u_status ON u.user_status_universal_uuid = u_status.universal_uuid
WHERE u.user_uuid = $1 AND u.is_deleted = false AND t.tenant_code = 'SYS-001'
`

type GetAdminRow struct {
	UserUuid     pgtype.UUID        `json:"user_uuid"`
	FirstName    string             `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	Username     string             `json:"username"`
	EmailAddress pgtype.Text        `json:"email_address"`
	Role         pgtype.Text        `json:"role"`
	RoleUuid     pgtype.UUID        `json:"role_uuid"`
	Status       pgtype.Text        `json:"status"`
	StatusUuid   pgtype.UUID        `json:"status_uuid"`
	MfaEnabled   bool               `json:"mfa_enabled"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) GetAdmin(ctx context.Context, userUuid pgtype.UUID) (GetAdminRow, error) {
	row := q.db.QueryRow(ctx, getAdmin, userUuid)
	var i GetAdminRow
	err := row.Scan(
		&i.UserUuid,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.EmailAddress,
		&i.Role,
		&i.RoleUuid,
		&i.Status,
		&i.StatusUuid,
		&i.MfaEnabled,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminStats = `-- name: GetAdminStats :one
SELECT 
    COUNT(*) AS total_users,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Active') AS active_users,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Inactive') AS inactive_users,
    COUNT(DISTINCT r.role_name) AS total_roles
FROM "user" u
JOIN user_tenant ut ON u.user_uuid = ut.user_uuid
JOIN tenant t ON ut.tenant_uuid = t.tenant_uuid
LEFT JOIN user_workspace uw ON ut.user_tenant_uuid = uw.user_tenant_uuid
LEFT JOIN role r ON uw.role_uuid = r.role_uuid
LEFT JOIN mst_universal u_status ON u.user_status_universal_uuid = u_status.universal_uuid
WHERE u.is_deleted = false AND t.tenant_code = 'SYS-001'
`

type GetAdminStatsRow struct {
	TotalUsers    int64 `json:"total_users"`
	ActiveUsers   int64 `json:"active_users"`
	InactiveUsers int64 `json:"inactive_users"`
	TotalRoles    int64 `json:"total_roles"`
}

func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.ActiveUsers,
		&i.InactiveUsers,
		&i.TotalRoles,
	)
	return i, err
}

const getTenantByCode = `-- name: GetTenantByCode :one
SELECT tenant_uuid FROM tenant WHERE tenant_code = $1 LIMIT 1
`

func (q *Queries) GetTenantByCode(ctx context.Context, tenantCode string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getTenantByCode, tenantCode)
	var tenant_uuid pgtype.UUID
	err := row.Scan(&tenant_uuid)
	return tenant_uuid, err
}

const listAdminsPaginated = `-- name: ListAdminsPaginated :many
SELECT 
    u.user_uuid,
    u.first_name,
    u.last_name,
    ua.login_id AS username,
    u.email_address,
    r.role_name AS role,
    COALESCE(u_status.value_name, 'Unknown') AS status,
    CASE WHEN ua.is_mobile_verified THEN 'Enabled' ELSE 'Disabled' END AS mfa,
    ua.last_login_at,
    COUNT(*) OVER() AS total_records
FROM "user" u
JOIN user_auth ua ON u.user_uuid = ua.user_uuid
JOIN user_tenant ut ON u.user_uuid = ut.user_uuid
JOIN tenant t ON ut.tenant_uuid = t.tenant_uuid
LEFT JOIN user_workspace uw ON ut.user_tenant_uuid = uw.user_tenant_uuid
LEFT JOIN role r ON uw.role_uuid = r.role_uuid
LEFT JOIN mst_universal u_status ON u.user_status_universal_uuid = u_status.universal_uuid
WHERE 
    u.is_deleted = false
    AND t.tenant_code = 'SYS-001'
    AND ($1::text = '' OR u.first_name ILIKE '%' || $1 || '%' OR u.last_name ILIKE '%' || $1 || '%' OR u.email_address ILIKE '%' || $1 || '%' OR ua.login_id ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR r.role_name = $2)
    AND ($3::text = '' OR u_status.value_name = $3)
    AND ($4::text = '' OR (CASE WHEN ua.is_mobile_verified THEN 'Enabled' ELSE 'Disabled' END) = $4)
ORDER BY u.created_at DESC
LIMIT $6 OFFSET $5
`

type ListAdminsPaginatedParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Offset  int32  `json:"offset"`
	Limit   int32  `json:"limit"`
}

type ListAdminsPaginatedRow struct {
	UserUuid     pgtype.UUID        `json:"user_uuid"`
	FirstName    string             `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	Username     string             `json:"username"`
	EmailAddress pgtype.Text        `json:"email_address"`
	Role         pgtype.Text        `json:"role"`
	Status       string             `json:"status"`
	Mfa          string             `json:"mfa"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	TotalRecords int64              `json:"total_records"`
}

func (q *Queries) ListAdminsPaginated(ctx context.Context, arg ListAdminsPaginatedParams) ([]ListAdminsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listAdminsPaginated,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminsPaginatedRow
	for rows.Next() {
		var i ListAdminsPaginatedRow
		if err := rows.Scan(
			&i.UserUuid,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.EmailAddress,
			&i.Role,
			&i.Status,
			&i.Mfa,
			&i.LastLoginAt,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminAuth = `-- name: UpdateAdminAuth :exec
UPDATE user_auth SET
    login_id = $2,
    password_hash = COALESCE(NULLIF($3::text, ''), password_hash),
    is_mobile_verified = $4,
    updated_at = NOW()
WHERE user_uuid = $1
`

type UpdateAdminAuthParams struct {
	UserUuid         pgtype.UUID `json:"user_uuid"`
	LoginID          string      `json:"login_id"`
	Column3          string      `json:"column_3"`
	IsMobileVerified bool        `json:"is_mobile_verified"`
}

func (q *Queries) UpdateAdminAuth(ctx context.Context, arg UpdateAdminAuthParams) error {
	_, err := q.db.Exec(ctx, updateAdminAuth,
		arg.UserUuid,
		arg.LoginID,
		arg.Column3,
		arg.IsMobileVerified,
	)
	return err
}

const updateAdminUser = `-- name: UpdateAdminUser :exec
UPDATE "user" SET
    first_name = $2,
    last_name = $3,
    email_address = $4,
    user_status_universal_uuid = $5,
    updated_at = NOW(),
    updated_by_user_uuid = $6
WHERE user_uuid = $1
`

type UpdateAdminUserParams struct {
	UserUuid                pgtype.UUID `json:"user_uuid"`
	FirstName               string      `json:"first_name"`
	LastName                pgtype.Text `json:"last_name"`
	EmailAddress            pgtype.Text `json:"email_address"`
	UserStatusUniversalUuid pgtype.UUID `json:"user_status_universal_uuid"`
	UpdatedByUserUuid       pgtype.UUID `json:"updated_by_user_uuid"`
}

func (q *Queries) UpdateAdminUser(ctx context.Context, arg UpdateAdminUserParams) error {
	_, err := q.db.Exec(ctx, updateAdminUser,
		arg.UserUuid,
		arg.FirstName,
		arg.LastName,
		arg.EmailAddress,
		arg.UserStatusUniversalUuid,
		arg.UpdatedByUserUuid,
	)
	return err
}

const updateAdminWorkspace = `-- name: UpdateAdminWorkspace :exec
UPDATE user_workspace SET
    role_uuid = $2
WHERE user_tenant_uuid = (
    SELECT user_tenant_uuid FROM user_tenant WHERE user_uuid = $1 LIMIT 1
)
`

type UpdateAdminWorkspaceParams struct {
	UserUuid pgtype.UUID `json:"user_uuid"`
	RoleUuid pgtype.UUID `json:"role_uuid"`
}

func (q *Queries) UpdateAdminWorkspace(ctx context.Context, arg UpdateAdminWorkspaceParams) error {
	_, err := q.db.Exec(ctx, updateAdminWorkspace, arg.UserUuid, arg.RoleUuid)
	return err
}
