// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: casbin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllRolePermissions = `-- name: GetAllRolePermissions :many
SELECT 
    rp.role_uuid,
    p.permission_code
FROM role_permission rp
JOIN role r ON rp.role_uuid = r.role_uuid
JOIN mst_permission p ON rp.permission_uuid = p.permission_uuid
WHERE rp.is_granted = TRUE AND rp.is_deleted = FALSE AND r.is_deleted = FALSE AND p.deleted_at IS NULL
`

type GetAllRolePermissionsRow struct {
	RoleUuid       pgtype.UUID `json:"role_uuid"`
	PermissionCode string      `json:"permission_code"`
}

func (q *Queries) GetAllRolePermissions(ctx context.Context) ([]GetAllRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getAllRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRolePermissionsRow
	for rows.Next() {
		var i GetAllRolePermissionsRow
		if err := rows.Scan(&i.RoleUuid, &i.PermissionCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
