// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT 
    (SELECT count(*) FROM "user")::int AS total_users,
    (SELECT count(*) FROM tenant)::int AS total_tenants,
    (SELECT count(*) FROM tenant_subscription)::int AS total_subscriptions
`

type GetDashboardStatsRow struct {
	TotalUsers         int32 `json:"total_users"`
	TotalTenants       int32 `json:"total_tenants"`
	TotalSubscriptions int32 `json:"total_subscriptions"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(&i.TotalUsers, &i.TotalTenants, &i.TotalSubscriptions)
	return i, err
}
