// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGatewayStats = `-- name: GetGatewayStats :one
SELECT 
    COUNT(*) AS total_transactions,
    COALESCE(SUM(amount), 0) AS total_amount,
    COALESCE(SUM(amount) FILTER (WHERE u_status.value_name = 'Paid'), 0) AS success_amount,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Paid') AS success_count,
    COALESCE(SUM(amount) FILTER (WHERE u_status.value_name = 'Failed'), 0) AS failed_amount,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Failed') AS failed_count,
    COALESCE(SUM(amount) FILTER (WHERE u_status.value_name = 'Pending'), 0) AS pending_amount,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Pending') AS pending_count
FROM tenant_subscription_payment p
LEFT JOIN mst_universal u_status ON p.payment_status_universal_uuid = u_status.universal_uuid
WHERE p.is_deleted = false
`

type GetGatewayStatsRow struct {
	TotalTransactions int64       `json:"total_transactions"`
	TotalAmount       interface{} `json:"total_amount"`
	SuccessAmount     interface{} `json:"success_amount"`
	SuccessCount      int64       `json:"success_count"`
	FailedAmount      interface{} `json:"failed_amount"`
	FailedCount       int64       `json:"failed_count"`
	PendingAmount     interface{} `json:"pending_amount"`
	PendingCount      int64       `json:"pending_count"`
}

func (q *Queries) GetGatewayStats(ctx context.Context) (GetGatewayStatsRow, error) {
	row := q.db.QueryRow(ctx, getGatewayStats)
	var i GetGatewayStatsRow
	err := row.Scan(
		&i.TotalTransactions,
		&i.TotalAmount,
		&i.SuccessAmount,
		&i.SuccessCount,
		&i.FailedAmount,
		&i.FailedCount,
		&i.PendingAmount,
		&i.PendingCount,
	)
	return i, err
}

const getGatewayTransaction = `-- name: GetGatewayTransaction :one
SELECT 
    p.tenant_subscription_payment_uuid,
    p.payment_number AS transaction_id,
    COALESCE(u_mode.value_name, 'Unknown') AS gateway,
    t.tenant_name AS customer,
    t.email_address,
    COALESCE(pl.plan_name, 'None') AS plan_name,
    p.amount,
    COALESCE(u_status.value_name, 'Unknown') AS payment_status,
    p.created_at
FROM tenant_subscription_payment p
JOIN tenant t ON p.tenant_uuid = t.tenant_uuid
LEFT JOIN tenant_subscription ts ON p.tenant_subscription_uuid = ts.tenant_subscription_uuid
LEFT JOIN mst_plan_price pp ON ts.plan_price_uuid = pp.plan_price_uuid
LEFT JOIN mst_plan pl ON pp.plan_uuid = pl.plan_uuid
LEFT JOIN mst_universal u_status ON p.payment_status_universal_uuid = u_status.universal_uuid
LEFT JOIN mst_universal u_mode ON p.payment_mode_universal_uuid = u_mode.universal_uuid
WHERE p.tenant_subscription_payment_uuid = $1 AND p.is_deleted = false
`

type GetGatewayTransactionRow struct {
	TenantSubscriptionPaymentUuid pgtype.UUID        `json:"tenant_subscription_payment_uuid"`
	TransactionID                 string             `json:"transaction_id"`
	Gateway                       string             `json:"gateway"`
	Customer                      string             `json:"customer"`
	EmailAddress                  pgtype.Text        `json:"email_address"`
	PlanName                      string             `json:"plan_name"`
	Amount                        pgtype.Numeric     `json:"amount"`
	PaymentStatus                 string             `json:"payment_status"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetGatewayTransaction(ctx context.Context, tenantSubscriptionPaymentUuid pgtype.UUID) (GetGatewayTransactionRow, error) {
	row := q.db.QueryRow(ctx, getGatewayTransaction, tenantSubscriptionPaymentUuid)
	var i GetGatewayTransactionRow
	err := row.Scan(
		&i.TenantSubscriptionPaymentUuid,
		&i.TransactionID,
		&i.Gateway,
		&i.Customer,
		&i.EmailAddress,
		&i.PlanName,
		&i.Amount,
		&i.PaymentStatus,
		&i.CreatedAt,
	)
	return i, err
}

const listGatewayTransactionsPaginated = `-- name: ListGatewayTransactionsPaginated :many
SELECT 
    p.tenant_subscription_payment_uuid,
    p.payment_number AS transaction_id,
    COALESCE(u_mode.value_name, 'Unknown') AS gateway,
    t.tenant_name AS customer,
    t.email_address,
    COALESCE(pl.plan_name, 'None') AS plan_name,
    p.amount,
    COALESCE(u_status.value_name, 'Unknown') AS payment_status,
    p.created_at,
    COUNT(*) OVER() AS total_records
FROM tenant_subscription_payment p
JOIN tenant t ON p.tenant_uuid = t.tenant_uuid
LEFT JOIN tenant_subscription ts ON p.tenant_subscription_uuid = ts.tenant_subscription_uuid
LEFT JOIN mst_plan_price pp ON ts.plan_price_uuid = pp.plan_price_uuid
LEFT JOIN mst_plan pl ON pp.plan_uuid = pl.plan_uuid
LEFT JOIN mst_universal u_status ON p.payment_status_universal_uuid = u_status.universal_uuid
LEFT JOIN mst_universal u_mode ON p.payment_mode_universal_uuid = u_mode.universal_uuid
WHERE 
    p.is_deleted = false
    AND ($1::text = '' OR p.payment_number ILIKE '%' || $1 || '%' OR t.tenant_name ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR u_mode.value_name = $2)
    AND ($3::text = '' OR u_status.value_name = $3)
    AND (
        ($6::text = '' OR $7::text = '') 
        OR 
        (p.created_at >= $6::date AND p.created_at <= $7::date)
    )
ORDER BY p.created_at DESC
LIMIT $5 OFFSET $4
`

type ListGatewayTransactionsPaginatedParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Offset  int32  `json:"offset"`
	Limit   int32  `json:"limit"`
	Column6 string `json:"column_6"`
	Column7 string `json:"column_7"`
}

type ListGatewayTransactionsPaginatedRow struct {
	TenantSubscriptionPaymentUuid pgtype.UUID        `json:"tenant_subscription_payment_uuid"`
	TransactionID                 string             `json:"transaction_id"`
	Gateway                       string             `json:"gateway"`
	Customer                      string             `json:"customer"`
	EmailAddress                  pgtype.Text        `json:"email_address"`
	PlanName                      string             `json:"plan_name"`
	Amount                        pgtype.Numeric     `json:"amount"`
	PaymentStatus                 string             `json:"payment_status"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	TotalRecords                  int64              `json:"total_records"`
}

func (q *Queries) ListGatewayTransactionsPaginated(ctx context.Context, arg ListGatewayTransactionsPaginatedParams) ([]ListGatewayTransactionsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listGatewayTransactionsPaginated,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Offset,
		arg.Limit,
		arg.Column6,
		arg.Column7,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGatewayTransactionsPaginatedRow
	for rows.Next() {
		var i ListGatewayTransactionsPaginatedRow
		if err := rows.Scan(
			&i.TenantSubscriptionPaymentUuid,
			&i.TransactionID,
			&i.Gateway,
			&i.Customer,
			&i.EmailAddress,
			&i.PlanName,
			&i.Amount,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
