// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRolePermission = `-- name: AssignRolePermission :exec
INSERT INTO role_permissions (
    role_id, permission_id
) VALUES (
    $1, $2
)
`

type AssignRolePermissionParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) AssignRolePermission(ctx context.Context, arg AssignRolePermissionParams) error {
	_, err := q.db.Exec(ctx, assignRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (
    id, name, description, created_at, updated_at
) VALUES (
    $1, $2, $3, now(), now()
)
`

type CreateRoleParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole, arg.ID, arg.Name, arg.Description)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, email, password_hash, tenant_id, role_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, now(), now()
)
`

type CreateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	RoleID       pgtype.UUID `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.TenantID,
		arg.RoleID,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, tenant_id, role_id, created_at, updated_at
FROM users
WHERE id = $1 AND archived_at IS NULL
`

type GetUserByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TenantID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
