// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInvoice = `-- name: GetInvoice :one
SELECT 
    p.tenant_subscription_payment_uuid AS invoice_uuid,
    p.payment_number AS invoice_no,
    t.tenant_name AS customer,
    t.email_address,
    COALESCE(u_type.value_name, 'Subscription') AS billing_type,
    p.created_at AS invoice_date,
    CAST(p.created_at + INTERVAL '10 days' AS timestamptz) AS due_date,
    p.amount,
    COALESCE(u_status.value_name, 'Unknown') AS status,
    p.payment_date
FROM tenant_subscription_payment p
JOIN tenant t ON p.tenant_uuid = t.tenant_uuid
LEFT JOIN tenant_subscription ts ON p.tenant_subscription_uuid = ts.tenant_subscription_uuid
LEFT JOIN mst_plan_price pp ON ts.plan_price_uuid = pp.plan_price_uuid
LEFT JOIN mst_plan pl ON pp.plan_uuid = pl.plan_uuid
LEFT JOIN mst_universal u_status ON p.payment_status_universal_uuid = u_status.universal_uuid
LEFT JOIN mst_universal u_type ON pl.plan_uuid = u_type.universal_uuid
WHERE p.tenant_subscription_payment_uuid = $1 AND p.is_deleted = false
`

type GetInvoiceRow struct {
	InvoiceUuid  pgtype.UUID        `json:"invoice_uuid"`
	InvoiceNo    string             `json:"invoice_no"`
	Customer     string             `json:"customer"`
	EmailAddress pgtype.Text        `json:"email_address"`
	BillingType  string             `json:"billing_type"`
	InvoiceDate  pgtype.Timestamptz `json:"invoice_date"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	Amount       pgtype.Numeric     `json:"amount"`
	Status       string             `json:"status"`
	PaymentDate  pgtype.Date        `json:"payment_date"`
}

func (q *Queries) GetInvoice(ctx context.Context, tenantSubscriptionPaymentUuid pgtype.UUID) (GetInvoiceRow, error) {
	row := q.db.QueryRow(ctx, getInvoice, tenantSubscriptionPaymentUuid)
	var i GetInvoiceRow
	err := row.Scan(
		&i.InvoiceUuid,
		&i.InvoiceNo,
		&i.Customer,
		&i.EmailAddress,
		&i.BillingType,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Amount,
		&i.Status,
		&i.PaymentDate,
	)
	return i, err
}

const getInvoiceStats = `-- name: GetInvoiceStats :one
SELECT 
    COUNT(*) AS total_invoices,
    COALESCE(SUM(amount) FILTER (WHERE u_status.value_name = 'Paid'), 0) AS paid_amount,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Paid') AS paid_count,
    COALESCE(SUM(amount) FILTER (WHERE u_status.value_name = 'Pending'), 0) AS pending_amount,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Pending') AS pending_count,
    COALESCE(SUM(amount) FILTER (WHERE u_status.value_name = 'Failed' OR u_status.value_name = 'Overdue'), 0) AS overdue_amount,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Failed' OR u_status.value_name = 'Overdue') AS overdue_count
FROM tenant_subscription_payment p
LEFT JOIN mst_universal u_status ON p.payment_status_universal_uuid = u_status.universal_uuid
WHERE p.is_deleted = false
`

type GetInvoiceStatsRow struct {
	TotalInvoices int64       `json:"total_invoices"`
	PaidAmount    interface{} `json:"paid_amount"`
	PaidCount     int64       `json:"paid_count"`
	PendingAmount interface{} `json:"pending_amount"`
	PendingCount  int64       `json:"pending_count"`
	OverdueAmount interface{} `json:"overdue_amount"`
	OverdueCount  int64       `json:"overdue_count"`
}

func (q *Queries) GetInvoiceStats(ctx context.Context) (GetInvoiceStatsRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceStats)
	var i GetInvoiceStatsRow
	err := row.Scan(
		&i.TotalInvoices,
		&i.PaidAmount,
		&i.PaidCount,
		&i.PendingAmount,
		&i.PendingCount,
		&i.OverdueAmount,
		&i.OverdueCount,
	)
	return i, err
}

const listInvoicesPaginated = `-- name: ListInvoicesPaginated :many
SELECT 
    p.tenant_subscription_payment_uuid AS invoice_uuid,
    p.payment_number AS invoice_no,
    t.tenant_name AS customer,
    t.email_address,
    COALESCE(u_type.value_name, 'Subscription') AS billing_type,
    p.created_at AS invoice_date,
    CAST(p.created_at + INTERVAL '10 days' AS timestamptz) AS due_date,
    p.amount,
    COALESCE(u_status.value_name, 'Unknown') AS status,
    p.payment_date,
    COUNT(*) OVER() AS total_records
FROM tenant_subscription_payment p
JOIN tenant t ON p.tenant_uuid = t.tenant_uuid
LEFT JOIN tenant_subscription ts ON p.tenant_subscription_uuid = ts.tenant_subscription_uuid
LEFT JOIN mst_plan_price pp ON ts.plan_price_uuid = pp.plan_price_uuid
LEFT JOIN mst_plan pl ON pp.plan_uuid = pl.plan_uuid
LEFT JOIN mst_universal u_status ON p.payment_status_universal_uuid = u_status.universal_uuid
LEFT JOIN mst_universal u_type ON pl.plan_uuid = u_type.universal_uuid -- Mocking billing type
WHERE 
    p.is_deleted = false
    AND ($1::text = '' OR p.payment_number ILIKE '%' || $1 || '%' OR t.tenant_name ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR u_status.value_name = $2)
    AND (
        ($5::text = '' OR $6::text = '') 
        OR 
        (p.created_at >= $5::date AND p.created_at <= $6::date)
    )
ORDER BY p.created_at DESC
LIMIT $4 OFFSET $3
`

type ListInvoicesPaginatedParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Offset  int32  `json:"offset"`
	Limit   int32  `json:"limit"`
	Column5 string `json:"column_5"`
	Column6 string `json:"column_6"`
}

type ListInvoicesPaginatedRow struct {
	InvoiceUuid  pgtype.UUID        `json:"invoice_uuid"`
	InvoiceNo    string             `json:"invoice_no"`
	Customer     string             `json:"customer"`
	EmailAddress pgtype.Text        `json:"email_address"`
	BillingType  string             `json:"billing_type"`
	InvoiceDate  pgtype.Timestamptz `json:"invoice_date"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	Amount       pgtype.Numeric     `json:"amount"`
	Status       string             `json:"status"`
	PaymentDate  pgtype.Date        `json:"payment_date"`
	TotalRecords int64              `json:"total_records"`
}

func (q *Queries) ListInvoicesPaginated(ctx context.Context, arg ListInvoicesPaginatedParams) ([]ListInvoicesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesPaginated,
		arg.Column1,
		arg.Column2,
		arg.Offset,
		arg.Limit,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesPaginatedRow
	for rows.Next() {
		var i ListInvoicesPaginatedRow
		if err := rows.Scan(
			&i.InvoiceUuid,
			&i.InvoiceNo,
			&i.Customer,
			&i.EmailAddress,
			&i.BillingType,
			&i.InvoiceDate,
			&i.DueDate,
			&i.Amount,
			&i.Status,
			&i.PaymentDate,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
