// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: master_type.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMasterType = `-- name: CreateMasterType :one
INSERT INTO mst_master_type (
    master_type_uuid,
    master_type_name,
    display_order,
    is_system,
    remarks,
    created_at,
    created_by_user_uuid,
    updated_at,
    updated_by_user_uuid
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $6, $7
) RETURNING master_type_uuid, master_type_name, display_order, is_system, remarks, created_at, created_by_user_uuid, updated_at, updated_by_user_uuid, is_archived, archived_at, archived_by_user_uuid, is_deleted, deleted_at, deleted_by_user_uuid
`

type CreateMasterTypeParams struct {
	MasterTypeUuid    pgtype.UUID        `json:"master_type_uuid"`
	MasterTypeName    string             `json:"master_type_name"`
	DisplayOrder      int32              `json:"display_order"`
	IsSystem          bool               `json:"is_system"`
	Remarks           pgtype.Text        `json:"remarks"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid pgtype.UUID        `json:"created_by_user_uuid"`
}

func (q *Queries) CreateMasterType(ctx context.Context, arg CreateMasterTypeParams) (MstMasterType, error) {
	row := q.db.QueryRow(ctx, createMasterType,
		arg.MasterTypeUuid,
		arg.MasterTypeName,
		arg.DisplayOrder,
		arg.IsSystem,
		arg.Remarks,
		arg.CreatedAt,
		arg.CreatedByUserUuid,
	)
	var i MstMasterType
	err := row.Scan(
		&i.MasterTypeUuid,
		&i.MasterTypeName,
		&i.DisplayOrder,
		&i.IsSystem,
		&i.Remarks,
		&i.CreatedAt,
		&i.CreatedByUserUuid,
		&i.UpdatedAt,
		&i.UpdatedByUserUuid,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ArchivedByUserUuid,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedByUserUuid,
	)
	return i, err
}

const deleteMasterType = `-- name: DeleteMasterType :exec
UPDATE mst_master_type
SET
    is_deleted = true,
    deleted_at = NOW(),
    deleted_by_user_uuid = $2
WHERE master_type_uuid = $1 AND is_deleted = false
`

type DeleteMasterTypeParams struct {
	MasterTypeUuid    pgtype.UUID `json:"master_type_uuid"`
	DeletedByUserUuid pgtype.UUID `json:"deleted_by_user_uuid"`
}

func (q *Queries) DeleteMasterType(ctx context.Context, arg DeleteMasterTypeParams) error {
	_, err := q.db.Exec(ctx, deleteMasterType, arg.MasterTypeUuid, arg.DeletedByUserUuid)
	return err
}

const getMasterType = `-- name: GetMasterType :one
SELECT master_type_uuid, master_type_name, display_order, is_system, remarks, created_at, created_by_user_uuid, updated_at, updated_by_user_uuid, is_archived, archived_at, archived_by_user_uuid, is_deleted, deleted_at, deleted_by_user_uuid FROM mst_master_type
WHERE master_type_uuid = $1 AND is_deleted = false
`

func (q *Queries) GetMasterType(ctx context.Context, masterTypeUuid pgtype.UUID) (MstMasterType, error) {
	row := q.db.QueryRow(ctx, getMasterType, masterTypeUuid)
	var i MstMasterType
	err := row.Scan(
		&i.MasterTypeUuid,
		&i.MasterTypeName,
		&i.DisplayOrder,
		&i.IsSystem,
		&i.Remarks,
		&i.CreatedAt,
		&i.CreatedByUserUuid,
		&i.UpdatedAt,
		&i.UpdatedByUserUuid,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ArchivedByUserUuid,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedByUserUuid,
	)
	return i, err
}

const listMasterTypes = `-- name: ListMasterTypes :many
SELECT master_type_uuid, master_type_name, display_order, is_system, remarks, created_at, created_by_user_uuid, updated_at, updated_by_user_uuid, is_archived, archived_at, archived_by_user_uuid, is_deleted, deleted_at, deleted_by_user_uuid FROM mst_master_type
WHERE is_deleted = false
ORDER BY display_order ASC
LIMIT $1 OFFSET $2
`

type ListMasterTypesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMasterTypes(ctx context.Context, arg ListMasterTypesParams) ([]MstMasterType, error) {
	rows, err := q.db.Query(ctx, listMasterTypes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MstMasterType
	for rows.Next() {
		var i MstMasterType
		if err := rows.Scan(
			&i.MasterTypeUuid,
			&i.MasterTypeName,
			&i.DisplayOrder,
			&i.IsSystem,
			&i.Remarks,
			&i.CreatedAt,
			&i.CreatedByUserUuid,
			&i.UpdatedAt,
			&i.UpdatedByUserUuid,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ArchivedByUserUuid,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.DeletedByUserUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMasterType = `-- name: UpdateMasterType :one
UPDATE mst_master_type
SET
    master_type_name = COALESCE($3, master_type_name),
    display_order = COALESCE($4, display_order),
    is_system = COALESCE($5, is_system),
    remarks = COALESCE($6, remarks),
    updated_at = NOW(),
    updated_by_user_uuid = $2
WHERE master_type_uuid = $1 AND is_deleted = false
RETURNING master_type_uuid, master_type_name, display_order, is_system, remarks, created_at, created_by_user_uuid, updated_at, updated_by_user_uuid, is_archived, archived_at, archived_by_user_uuid, is_deleted, deleted_at, deleted_by_user_uuid
`

type UpdateMasterTypeParams struct {
	MasterTypeUuid    pgtype.UUID `json:"master_type_uuid"`
	UpdatedByUserUuid pgtype.UUID `json:"updated_by_user_uuid"`
	MasterTypeName    pgtype.Text `json:"master_type_name"`
	DisplayOrder      pgtype.Int4 `json:"display_order"`
	IsSystem          pgtype.Bool `json:"is_system"`
	Remarks           pgtype.Text `json:"remarks"`
}

func (q *Queries) UpdateMasterType(ctx context.Context, arg UpdateMasterTypeParams) (MstMasterType, error) {
	row := q.db.QueryRow(ctx, updateMasterType,
		arg.MasterTypeUuid,
		arg.UpdatedByUserUuid,
		arg.MasterTypeName,
		arg.DisplayOrder,
		arg.IsSystem,
		arg.Remarks,
	)
	var i MstMasterType
	err := row.Scan(
		&i.MasterTypeUuid,
		&i.MasterTypeName,
		&i.DisplayOrder,
		&i.IsSystem,
		&i.Remarks,
		&i.CreatedAt,
		&i.CreatedByUserUuid,
		&i.UpdatedAt,
		&i.UpdatedByUserUuid,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ArchivedByUserUuid,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedByUserUuid,
	)
	return i, err
}
