// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ActivityUuid              pgtype.UUID        `json:"activity_uuid"`
	TenantUuid                pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid             pgtype.UUID        `json:"workspace_uuid"`
	OpportunityUuid           pgtype.UUID        `json:"opportunity_uuid"`
	ModuleUuid                pgtype.UUID        `json:"module_uuid"`
	EntityUuid                pgtype.UUID        `json:"entity_uuid"`
	ActivityTypeUniversalUuid pgtype.UUID        `json:"activity_type_universal_uuid"`
	StatusUuid                pgtype.UUID        `json:"status_uuid"`
	PriorityUniversalUuid     pgtype.UUID        `json:"priority_universal_uuid"`
	ActivityDatetime          pgtype.Timestamptz `json:"activity_datetime"`
	FollowupDatetime          pgtype.Timestamptz `json:"followup_datetime"`
	PerformedByUserUuid       pgtype.UUID        `json:"performed_by_user_uuid"`
	Remarks                   pgtype.Text        `json:"remarks"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid         pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid         pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                bool               `json:"is_archived"`
	ArchivedAt                pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid        pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                 bool               `json:"is_deleted"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid         pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type AuditLog struct {
	AuditLogUuid     pgtype.UUID        `json:"audit_log_uuid"`
	TenantUuid       pgtype.UUID        `json:"tenant_uuid"`
	ModuleUuid       pgtype.UUID        `json:"module_uuid"`
	EntityUuid       pgtype.UUID        `json:"entity_uuid"`
	ActionName       string             `json:"action_name"`
	OldValueJson     []byte             `json:"old_value_json"`
	NewValueJson     []byte             `json:"new_value_json"`
	ActionByUserUuid pgtype.UUID        `json:"action_by_user_uuid"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Booking struct {
	BookingUuid              pgtype.UUID        `json:"booking_uuid"`
	TenantUuid               pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid            pgtype.UUID        `json:"workspace_uuid"`
	StatusUuid               pgtype.UUID        `json:"status_uuid"`
	OpportunityUuid          pgtype.UUID        `json:"opportunity_uuid"`
	QuotationUuid            pgtype.UUID        `json:"quotation_uuid"`
	ContactUuid              pgtype.UUID        `json:"contact_uuid"`
	UnitUuid                 pgtype.UUID        `json:"unit_uuid"`
	PaymentPlanUniversalUuid pgtype.UUID        `json:"payment_plan_universal_uuid"`
	BookingNumber            string             `json:"booking_number"`
	BookingDate              pgtype.Date        `json:"booking_date"`
	AgreementValue           pgtype.Numeric     `json:"agreement_value"`
	ReceivedAmount           pgtype.Numeric     `json:"received_amount"`
	RefundedAmount           pgtype.Numeric     `json:"refunded_amount"`
	BalanceAmount            pgtype.Numeric     `json:"balance_amount"`
	BookingAmount            pgtype.Numeric     `json:"booking_amount"`
	LoanAmount               pgtype.Numeric     `json:"loan_amount"`
	LoanBankName             pgtype.Text        `json:"loan_bank_name"`
	CoApplicantDetails       []byte             `json:"co_applicant_details"`
	Remarks                  pgtype.Text        `json:"remarks"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid        pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid        pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived               bool               `json:"is_archived"`
	ArchivedAt               pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid       pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                bool               `json:"is_deleted"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid        pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type BookingCancellation struct {
	BookingCancellationUuid         pgtype.UUID        `json:"booking_cancellation_uuid"`
	TenantUuid                      pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid                   pgtype.UUID        `json:"workspace_uuid"`
	BookingUuid                     pgtype.UUID        `json:"booking_uuid"`
	CancellationReasonUniversalUuid pgtype.UUID        `json:"cancellation_reason_universal_uuid"`
	CancellationDate                pgtype.Date        `json:"cancellation_date"`
	RefundAmount                    pgtype.Numeric     `json:"refund_amount"`
	Remarks                         pgtype.Text        `json:"remarks"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid               pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid               pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                      bool               `json:"is_archived"`
	ArchivedAt                      pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid              pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                       bool               `json:"is_deleted"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid               pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type BookingCharge struct {
	BookingChargeUuid       pgtype.UUID        `json:"booking_charge_uuid"`
	TenantUuid              pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid           pgtype.UUID        `json:"workspace_uuid"`
	BookingUuid             pgtype.UUID        `json:"booking_uuid"`
	ChargeTypeUniversalUuid pgtype.UUID        `json:"charge_type_universal_uuid"`
	ChargeAmount            pgtype.Numeric     `json:"charge_amount"`
	Remarks                 pgtype.Text        `json:"remarks"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid       pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid       pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived              bool               `json:"is_archived"`
	ArchivedAt              pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid      pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted               bool               `json:"is_deleted"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid       pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type BookingDiscount struct {
	BookingDiscountUuid       pgtype.UUID        `json:"booking_discount_uuid"`
	TenantUuid                pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid             pgtype.UUID        `json:"workspace_uuid"`
	BookingUuid               pgtype.UUID        `json:"booking_uuid"`
	DiscountTypeUniversalUuid pgtype.UUID        `json:"discount_type_universal_uuid"`
	DiscountValue             pgtype.Numeric     `json:"discount_value"`
	Remarks                   pgtype.Text        `json:"remarks"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid         pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid         pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                bool               `json:"is_archived"`
	ArchivedAt                pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid        pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                 bool               `json:"is_deleted"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid         pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type BookingParking struct {
	BookingParkingUuid pgtype.UUID        `json:"booking_parking_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid      pgtype.UUID        `json:"workspace_uuid"`
	BookingUuid        pgtype.UUID        `json:"booking_uuid"`
	ParkingUuid        pgtype.UUID        `json:"parking_uuid"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type BookingPayment struct {
	BookingPaymentUuid         pgtype.UUID        `json:"booking_payment_uuid"`
	TenantUuid                 pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid              pgtype.UUID        `json:"workspace_uuid"`
	BookingUuid                pgtype.UUID        `json:"booking_uuid"`
	PaymentStatusUniversalUuid pgtype.UUID        `json:"payment_status_universal_uuid"`
	PaymentModeUniversalUuid   pgtype.UUID        `json:"payment_mode_universal_uuid"`
	ReceiptNumber              string             `json:"receipt_number"`
	ReceiptDate                pgtype.Date        `json:"receipt_date"`
	Amount                     pgtype.Numeric     `json:"amount"`
	ReferenceNumber            pgtype.Text        `json:"reference_number"`
	BankName                   pgtype.Text        `json:"bank_name"`
	ChequeDate                 pgtype.Date        `json:"cheque_date"`
	Remarks                    pgtype.Text        `json:"remarks"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid          pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid          pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                 bool               `json:"is_archived"`
	ArchivedAt                 pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid         pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                  bool               `json:"is_deleted"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid          pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type BookingRefund struct {
	BookingRefundUuid        pgtype.UUID        `json:"booking_refund_uuid"`
	TenantUuid               pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid            pgtype.UUID        `json:"workspace_uuid"`
	BookingUuid              pgtype.UUID        `json:"booking_uuid"`
	PaymentModeUniversalUuid pgtype.UUID        `json:"payment_mode_universal_uuid"`
	RefundNumber             string             `json:"refund_number"`
	RefundDate               pgtype.Date        `json:"refund_date"`
	RefundAmount             pgtype.Numeric     `json:"refund_amount"`
	ReferenceNumber          pgtype.Text        `json:"reference_number"`
	BankName                 pgtype.Text        `json:"bank_name"`
	Remarks                  pgtype.Text        `json:"remarks"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid        pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid        pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived               bool               `json:"is_archived"`
	ArchivedAt               pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid       pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                bool               `json:"is_deleted"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid        pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type BookingStorage struct {
	BookingStorageUuid pgtype.UUID        `json:"booking_storage_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid      pgtype.UUID        `json:"workspace_uuid"`
	BookingUuid        pgtype.UUID        `json:"booking_uuid"`
	StorageUuid        pgtype.UUID        `json:"storage_uuid"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type CallLog struct {
	CallLogUuid                pgtype.UUID        `json:"call_log_uuid"`
	TenantUuid                 pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid              pgtype.UUID        `json:"workspace_uuid"`
	UserUuid                   pgtype.UUID        `json:"user_uuid"`
	CallingListRecordUuid      pgtype.UUID        `json:"calling_list_record_uuid"`
	ActivityUuid               pgtype.UUID        `json:"activity_uuid"`
	ContactUuid                pgtype.UUID        `json:"contact_uuid"`
	LeadUuid                   pgtype.UUID        `json:"lead_uuid"`
	OpportunityUuid            pgtype.UUID        `json:"opportunity_uuid"`
	PhoneNumber                string             `json:"phone_number"`
	CallDirectionUniversalUuid pgtype.UUID        `json:"call_direction_universal_uuid"`
	CallStatusUniversalUuid    pgtype.UUID        `json:"call_status_universal_uuid"`
	CallStartDatetime          pgtype.Timestamptz `json:"call_start_datetime"`
	CallDate                   pgtype.Date        `json:"call_date"`
	CallEndDatetime            pgtype.Timestamptz `json:"call_end_datetime"`
	DurationSeconds            int32              `json:"duration_seconds"`
	IsKnownContact             bool               `json:"is_known_contact"`
	IsFromCallingList          bool               `json:"is_from_calling_list"`
	DeviceCallLogID            pgtype.Text        `json:"device_call_log_id"`
	SimSlot                    pgtype.Text        `json:"sim_slot"`
	Remarks                    pgtype.Text        `json:"remarks"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid          pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid          pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                 bool               `json:"is_archived"`
	ArchivedAt                 pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid         pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                  bool               `json:"is_deleted"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid          pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type CallingList struct {
	CallingListUuid             pgtype.UUID        `json:"calling_list_uuid"`
	TenantUuid                  pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid               pgtype.UUID        `json:"workspace_uuid"`
	CampaignUuid                pgtype.UUID        `json:"campaign_uuid"`
	CampaignImportUuid          pgtype.UUID        `json:"campaign_import_uuid"`
	SourceUniversalUuid         pgtype.UUID        `json:"source_universal_uuid"`
	CallingListName             string             `json:"calling_list_name"`
	AssignmentTypeUniversalUuid pgtype.UUID        `json:"assignment_type_universal_uuid"`
	AssignedRoleUuid            pgtype.UUID        `json:"assigned_role_uuid"`
	AssignedUserUuid            pgtype.UUID        `json:"assigned_user_uuid"`
	Remarks                     pgtype.Text        `json:"remarks"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid           pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid           pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                  bool               `json:"is_archived"`
	ArchivedAt                  pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid          pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                   bool               `json:"is_deleted"`
	DeletedAt                   pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid           pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type CallingListRecord struct {
	CallingListRecordUuid pgtype.UUID        `json:"calling_list_record_uuid"`
	TenantUuid            pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid         pgtype.UUID        `json:"workspace_uuid"`
	CallingListUuid       pgtype.UUID        `json:"calling_list_uuid"`
	ContactUuid           pgtype.UUID        `json:"contact_uuid"`
	LeadUuid              pgtype.UUID        `json:"lead_uuid"`
	OpportunityUuid       pgtype.UUID        `json:"opportunity_uuid"`
	AssignedUserUuid      pgtype.UUID        `json:"assigned_user_uuid"`
	PhoneNumber           string             `json:"phone_number"`
	NextCallDate          pgtype.Date        `json:"next_call_date"`
	LastCallAt            pgtype.Timestamptz `json:"last_call_at"`
	LastCallStatusUuid    pgtype.UUID        `json:"last_call_status_uuid"`
	CallCount             int32              `json:"call_count"`
	IsClosed              bool               `json:"is_closed"`
	Remarks               pgtype.Text        `json:"remarks"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid     pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid     pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived            bool               `json:"is_archived"`
	ArchivedAt            pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid    pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted             bool               `json:"is_deleted"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid     pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Campaign struct {
	CampaignUuid              pgtype.UUID        `json:"campaign_uuid"`
	TenantUuid                pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid             pgtype.UUID        `json:"workspace_uuid"`
	CampaignTypeUniversalUuid pgtype.UUID        `json:"campaign_type_universal_uuid"`
	StatusUuid                pgtype.UUID        `json:"status_uuid"`
	CampaignName              string             `json:"campaign_name"`
	StartDate                 pgtype.Date        `json:"start_date"`
	EndDate                   pgtype.Date        `json:"end_date"`
	EstimatedBudget           pgtype.Numeric     `json:"estimated_budget"`
	ActualBudget              pgtype.Numeric     `json:"actual_budget"`
	CampaignSettings          []byte             `json:"campaign_settings"`
	Remarks                   pgtype.Text        `json:"remarks"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid         pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid         pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                bool               `json:"is_archived"`
	ArchivedAt                pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid        pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                 bool               `json:"is_deleted"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid         pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type CampaignImport struct {
	CampaignImportUuid pgtype.UUID        `json:"campaign_import_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid      pgtype.UUID        `json:"workspace_uuid"`
	CampaignUuid       pgtype.UUID        `json:"campaign_uuid"`
	FileName           pgtype.Text        `json:"file_name"`
	TotalRecords       pgtype.Int4        `json:"total_records"`
	SuccessfulRecords  pgtype.Int4        `json:"successful_records"`
	FailedRecords      pgtype.Int4        `json:"failed_records"`
	ImportSummary      []byte             `json:"import_summary"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type CampaignMember struct {
	CampaignMemberUuid pgtype.UUID        `json:"campaign_member_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid      pgtype.UUID        `json:"workspace_uuid"`
	CampaignUuid       pgtype.UUID        `json:"campaign_uuid"`
	ContactUuid        pgtype.UUID        `json:"contact_uuid"`
	LeadUuid           pgtype.UUID        `json:"lead_uuid"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Commission struct {
	CommissionUuid       pgtype.UUID        `json:"commission_uuid"`
	TenantUuid           pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid        pgtype.UUID        `json:"workspace_uuid"`
	ModuleUuid           pgtype.UUID        `json:"module_uuid"`
	EntityUuid           pgtype.UUID        `json:"entity_uuid"`
	UserUuid             pgtype.UUID        `json:"user_uuid"`
	CommissionType       string             `json:"commission_type"`
	CommissionPercentage pgtype.Numeric     `json:"commission_percentage"`
	CommissionAmount     pgtype.Numeric     `json:"commission_amount"`
	StatusUuid           pgtype.UUID        `json:"status_uuid"`
	Remarks              pgtype.Text        `json:"remarks"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid    pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid    pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived           bool               `json:"is_archived"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid   pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted            bool               `json:"is_deleted"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid    pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type CommissionPayment struct {
	CommissionPaymentUuid      pgtype.UUID        `json:"commission_payment_uuid"`
	TenantUuid                 pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid              pgtype.UUID        `json:"workspace_uuid"`
	CommissionUuid             pgtype.UUID        `json:"commission_uuid"`
	UserUuid                   pgtype.UUID        `json:"user_uuid"`
	PaymentModeUniversalUuid   pgtype.UUID        `json:"payment_mode_universal_uuid"`
	PaymentStatusUniversalUuid pgtype.UUID        `json:"payment_status_universal_uuid"`
	PaymentNumber              string             `json:"payment_number"`
	PaymentDate                pgtype.Date        `json:"payment_date"`
	Amount                     pgtype.Numeric     `json:"amount"`
	ReferenceNumber            pgtype.Text        `json:"reference_number"`
	BankName                   pgtype.Text        `json:"bank_name"`
	Remarks                    pgtype.Text        `json:"remarks"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid          pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid          pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                 bool               `json:"is_archived"`
	ArchivedAt                 pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid         pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                  bool               `json:"is_deleted"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid          pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Contact struct {
	ContactUuid         pgtype.UUID        `json:"contact_uuid"`
	TenantUuid          pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid       pgtype.UUID        `json:"workspace_uuid"`
	OwnerUserUuid       pgtype.UUID        `json:"owner_user_uuid"`
	FullName            string             `json:"full_name"`
	MobileNumbers       []byte             `json:"mobile_numbers"`
	EmailAddresses      []byte             `json:"email_addresses"`
	Addresses           []byte             `json:"addresses"`
	RelationshipDetails []byte             `json:"relationship_details"`
	ContactSearchText   pgtype.Text        `json:"contact_search_text"`
	CompanyName         pgtype.Text        `json:"company_name"`
	Occupation          pgtype.Text        `json:"occupation"`
	BirthDate           pgtype.Date        `json:"birth_date"`
	AnniversaryDate     pgtype.Date        `json:"anniversary_date"`
	Remarks             pgtype.Text        `json:"remarks"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid   pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid   pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived          bool               `json:"is_archived"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid  pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted           bool               `json:"is_deleted"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid   pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Document struct {
	DocumentUuid              pgtype.UUID        `json:"document_uuid"`
	TenantUuid                pgtype.UUID        `json:"tenant_uuid"`
	ModuleUuid                pgtype.UUID        `json:"module_uuid"`
	EntityUuid                pgtype.UUID        `json:"entity_uuid"`
	DocumentTypeUniversalUuid pgtype.UUID        `json:"document_type_universal_uuid"`
	DocumentTitle             pgtype.Text        `json:"document_title"`
	OriginalFileName          string             `json:"original_file_name"`
	StoredFileName            string             `json:"stored_file_name"`
	FileExtension             pgtype.Text        `json:"file_extension"`
	MimeType                  pgtype.Text        `json:"mime_type"`
	FileSize                  pgtype.Int8        `json:"file_size"`
	FilePath                  string             `json:"file_path"`
	Remarks                   pgtype.Text        `json:"remarks"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid         pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid         pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                bool               `json:"is_archived"`
	ArchivedAt                pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid        pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                 bool               `json:"is_deleted"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid         pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Lead struct {
	LeadUuid            pgtype.UUID        `json:"lead_uuid"`
	TenantUuid          pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid       pgtype.UUID        `json:"workspace_uuid"`
	ContactUuid         pgtype.UUID        `json:"contact_uuid"`
	SourceUniversalUuid pgtype.UUID        `json:"source_universal_uuid"`
	CampaignUuid        pgtype.UUID        `json:"campaign_uuid"`
	PropertyUuid        pgtype.UUID        `json:"property_uuid"`
	AssignedUserUuid    pgtype.UUID        `json:"assigned_user_uuid"`
	VisibilityUserUuid  pgtype.UUID        `json:"visibility_user_uuid"`
	EnquiryDate         pgtype.Timestamptz `json:"enquiry_date"`
	Remarks             pgtype.Text        `json:"remarks"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid   pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid   pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived          bool               `json:"is_archived"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid  pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted           bool               `json:"is_deleted"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid   pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Medium struct {
	MediaUuid          pgtype.UUID        `json:"media_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid      pgtype.UUID        `json:"workspace_uuid"`
	ModuleUuid         pgtype.UUID        `json:"module_uuid"`
	EntityUuid         pgtype.UUID        `json:"entity_uuid"`
	PropertyBlockUuid  pgtype.UUID        `json:"property_block_uuid"`
	UnitUuid           pgtype.UUID        `json:"unit_uuid"`
	PropertyUuid       pgtype.UUID        `json:"property_uuid"`
	MediaTypeUuid      pgtype.UUID        `json:"media_type_uuid"`
	Title              pgtype.Text        `json:"title"`
	Description        pgtype.Text        `json:"description"`
	FileName           pgtype.Text        `json:"file_name"`
	OriginalFileName   pgtype.Text        `json:"original_file_name"`
	FileExtension      pgtype.Text        `json:"file_extension"`
	MimeType           pgtype.Text        `json:"mime_type"`
	FileSize           pgtype.Int8        `json:"file_size"`
	FileUrl            pgtype.Text        `json:"file_url"`
	ThumbnailUrl       pgtype.Text        `json:"thumbnail_url"`
	YoutubeUrl         pgtype.Text        `json:"youtube_url"`
	ExternalUrl        pgtype.Text        `json:"external_url"`
	EmbedUrl           pgtype.Text        `json:"embed_url"`
	DisplayOrder       int32              `json:"display_order"`
	IsFeatured         bool               `json:"is_featured"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
	TagsJson           []byte             `json:"tags_json"`
}

type MessageLog struct {
	MessageLogUuid              pgtype.UUID        `json:"message_log_uuid"`
	TenantUuid                  pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid               pgtype.UUID        `json:"workspace_uuid"`
	ModuleUuid                  pgtype.UUID        `json:"module_uuid"`
	EntityUuid                  pgtype.UUID        `json:"entity_uuid"`
	MessageChannelUniversalUuid pgtype.UUID        `json:"message_channel_universal_uuid"`
	Recipient                   string             `json:"recipient"`
	Subject                     pgtype.Text        `json:"subject"`
	MessageBody                 pgtype.Text        `json:"message_body"`
	ExternalReference           pgtype.Text        `json:"external_reference"`
	StatusUuid                  pgtype.UUID        `json:"status_uuid"`
	SentAt                      pgtype.Timestamptz `json:"sent_at"`
	DeliveredAt                 pgtype.Timestamptz `json:"delivered_at"`
	FailedAt                    pgtype.Timestamptz `json:"failed_at"`
	ErrorMessage                pgtype.Text        `json:"error_message"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
}

type MessageQueue struct {
	MessageQueueUuid            pgtype.UUID        `json:"message_queue_uuid"`
	TenantUuid                  pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid               pgtype.UUID        `json:"workspace_uuid"`
	ModuleUuid                  pgtype.UUID        `json:"module_uuid"`
	EntityUuid                  pgtype.UUID        `json:"entity_uuid"`
	MessageChannelUniversalUuid pgtype.UUID        `json:"message_channel_universal_uuid"`
	MessageTemplateUuid         pgtype.UUID        `json:"message_template_uuid"`
	Recipient                   pgtype.Text        `json:"recipient"`
	Subject                     pgtype.Text        `json:"subject"`
	MessageBody                 pgtype.Text        `json:"message_body"`
	PayloadJson                 []byte             `json:"payload_json"`
	RetryCount                  int32              `json:"retry_count"`
	SentAt                      pgtype.Timestamptz `json:"sent_at"`
	FailedAt                    pgtype.Timestamptz `json:"failed_at"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
}

type MessageTemplate struct {
	MessageTemplateUuid         pgtype.UUID        `json:"message_template_uuid"`
	TenantUuid                  pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid               pgtype.UUID        `json:"workspace_uuid"`
	MessageChannelUniversalUuid pgtype.UUID        `json:"message_channel_universal_uuid"`
	TemplateName                string             `json:"template_name"`
	TemplateSubject             pgtype.Text        `json:"template_subject"`
	TemplateBody                string             `json:"template_body"`
	VariableListJson            []byte             `json:"variable_list_json"`
	IsSystem                    bool               `json:"is_system"`
	Remarks                     pgtype.Text        `json:"remarks"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid           pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid           pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                  bool               `json:"is_archived"`
	ArchivedAt                  pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid          pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                   bool               `json:"is_deleted"`
	DeletedAt                   pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid           pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type MstAddon struct {
	AddonUuid  pgtype.UUID        `json:"addon_uuid"`
	Name       string             `json:"name"`
	Category   string             `json:"category"`
	AddonLimit string             `json:"addon_limit"`
	Price      string             `json:"price"`
	Status     string             `json:"status"`
	IconSvg    pgtype.Text        `json:"icon_svg"`
	IconColor  pgtype.Text        `json:"icon_color"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	IsDeleted  bool               `json:"is_deleted"`
}

type MstCurrency struct {
	CurrencyUuid       pgtype.UUID        `json:"currency_uuid"`
	CurrencyCode       string             `json:"currency_code"`
	CurrencyName       string             `json:"currency_name"`
	CurrencySymbol     pgtype.Text        `json:"currency_symbol"`
	SortOrder          int32              `json:"sort_order"`
	IsSystem           bool               `json:"is_system"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type MstMasterType struct {
	MasterTypeUuid     pgtype.UUID        `json:"master_type_uuid"`
	MasterTypeName     string             `json:"master_type_name"`
	DisplayOrder       int32              `json:"display_order"`
	IsSystem           bool               `json:"is_system"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type MstModule struct {
	ModuleUuid         pgtype.UUID        `json:"module_uuid"`
	ModuleName         string             `json:"module_name"`
	IsSystem           bool               `json:"is_system"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type MstPermission struct {
	PermissionUuid     pgtype.UUID        `json:"permission_uuid"`
	PermissionCode     string             `json:"permission_code"`
	PermissionName     string             `json:"permission_name"`
	SortOrder          int32              `json:"sort_order"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type MstPlan struct {
	PlanUuid               pgtype.UUID        `json:"plan_uuid"`
	PlanTypeUniversalUuid  pgtype.UUID        `json:"plan_type_universal_uuid"`
	PlanName               string             `json:"plan_name"`
	MaxUsers               int32              `json:"max_users"`
	DefaultStorageBytes    int64              `json:"default_storage_bytes"`
	DefaultSmsCredits      int32              `json:"default_sms_credits"`
	DefaultWhatsappCredits int32              `json:"default_whatsapp_credits"`
	DefaultEmailCredits    int32              `json:"default_email_credits"`
	SortOrder              int32              `json:"sort_order"`
	IsSystem               bool               `json:"is_system"`
	Remarks                pgtype.Text        `json:"remarks"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid      pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid      pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt             pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid     pgtype.UUID        `json:"archived_by_user_uuid"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid      pgtype.UUID        `json:"deleted_by_user_uuid"`
	IsDefault              bool               `json:"is_default"`
}

type MstPlanPrice struct {
	PlanPriceUuid             pgtype.UUID        `json:"plan_price_uuid"`
	PlanUuid                  pgtype.UUID        `json:"plan_uuid"`
	BillingCycleUniversalUuid pgtype.UUID        `json:"billing_cycle_universal_uuid"`
	PriceAmount               pgtype.Numeric     `json:"price_amount"`
	EffectiveFromDate         pgtype.Date        `json:"effective_from_date"`
	EffectiveToDate           pgtype.Date        `json:"effective_to_date"`
	IsForceMigration          bool               `json:"is_force_migration"`
	Remarks                   pgtype.Text        `json:"remarks"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid         pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid         pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt                pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid        pgtype.UUID        `json:"archived_by_user_uuid"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid         pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type MstStatus struct {
	StatusUuid         pgtype.UUID        `json:"status_uuid"`
	ModuleUuid         pgtype.UUID        `json:"module_uuid"`
	StatusName         string             `json:"status_name"`
	SortOrder          int32              `json:"sort_order"`
	ColorCode          pgtype.Text        `json:"color_code"`
	IsSystem           bool               `json:"is_system"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type MstUniversal struct {
	UniversalUuid       pgtype.UUID        `json:"universal_uuid"`
	TenantUuid          pgtype.UUID        `json:"tenant_uuid"`
	MasterTypeUuid      pgtype.UUID        `json:"master_type_uuid"`
	ParentUniversalUuid pgtype.UUID        `json:"parent_universal_uuid"`
	ValueName           string             `json:"value_name"`
	DisplayOrder        int32              `json:"display_order"`
	IsSystem            bool               `json:"is_system"`
	Remarks             pgtype.Text        `json:"remarks"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid   pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid   pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived          bool               `json:"is_archived"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid  pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted           bool               `json:"is_deleted"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid   pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Note struct {
	NoteUuid           pgtype.UUID        `json:"note_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	ModuleUuid         pgtype.UUID        `json:"module_uuid"`
	EntityUuid         pgtype.UUID        `json:"entity_uuid"`
	NoteText           string             `json:"note_text"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Opportunity struct {
	OpportunityUuid               pgtype.UUID        `json:"opportunity_uuid"`
	TenantUuid                    pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid                 pgtype.UUID        `json:"workspace_uuid"`
	ContactUuid                   pgtype.UUID        `json:"contact_uuid"`
	LeadUuid                      pgtype.UUID        `json:"lead_uuid"`
	PropertyUuid                  pgtype.UUID        `json:"property_uuid"`
	AssignedUserUuid              pgtype.UUID        `json:"assigned_user_uuid"`
	OpportunityStageUniversalUuid pgtype.UUID        `json:"opportunity_stage_universal_uuid"`
	ExpectedBudget                pgtype.Numeric     `json:"expected_budget"`
	ExpectedClosingDate           pgtype.Date        `json:"expected_closing_date"`
	NextFollowupDatetime          pgtype.Timestamptz `json:"next_followup_datetime"`
	Remarks                       pgtype.Text        `json:"remarks"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid             pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid             pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                    bool               `json:"is_archived"`
	ArchivedAt                    pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid            pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                     bool               `json:"is_deleted"`
	DeletedAt                     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid             pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Parking struct {
	ParkingUuid              pgtype.UUID        `json:"parking_uuid"`
	TenantUuid               pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid            pgtype.UUID        `json:"workspace_uuid"`
	PropertyBlockUuid        pgtype.UUID        `json:"property_block_uuid"`
	ParkingTypeUniversalUuid pgtype.UUID        `json:"parking_type_universal_uuid"`
	ParkingNumber            string             `json:"parking_number"`
	IsBooked                 bool               `json:"is_booked"`
	Remarks                  pgtype.Text        `json:"remarks"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid        pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid        pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived               bool               `json:"is_archived"`
	ArchivedAt               pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid       pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                bool               `json:"is_deleted"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid        pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Property struct {
	PropertyUuid                pgtype.UUID        `json:"property_uuid"`
	TenantUuid                  pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid               pgtype.UUID        `json:"workspace_uuid"`
	OwnerUserUuid               pgtype.UUID        `json:"owner_user_uuid"`
	PropertyTitle               string             `json:"property_title"`
	PublicSlug                  pgtype.Text        `json:"public_slug"`
	PublicUrlToken              pgtype.Text        `json:"public_url_token"`
	IsPublicListing             bool               `json:"is_public_listing"`
	UnitTypeUniversalUuid       pgtype.UUID        `json:"unit_type_universal_uuid"`
	PropertyStatusUniversalUuid pgtype.UUID        `json:"property_status_universal_uuid"`
	SourceUniversalUuid         pgtype.UUID        `json:"source_universal_uuid"`
	ListingType                 string             `json:"listing_type"`
	ExpectedPrice               pgtype.Numeric     `json:"expected_price"`
	ExpectedRent                pgtype.Numeric     `json:"expected_rent"`
	CarpetArea                  pgtype.Numeric     `json:"carpet_area"`
	BuiltupArea                 pgtype.Numeric     `json:"builtup_area"`
	SaleableArea                pgtype.Numeric     `json:"saleable_area"`
	AreaUnitUniversalUuid       pgtype.UUID        `json:"area_unit_universal_uuid"`
	FloorNumber                 pgtype.Int4        `json:"floor_number"`
	TotalFloors                 pgtype.Int4        `json:"total_floors"`
	FacingDetails               []byte             `json:"facing_details"`
	AmenityDetails              []byte             `json:"amenity_details"`
	AddressDetails              []byte             `json:"address_details"`
	ContactPersonDetails        []byte             `json:"contact_person_details"`
	AvailableFrom               pgtype.Date        `json:"available_from"`
	Remarks                     pgtype.Text        `json:"remarks"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid           pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid           pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                  bool               `json:"is_archived"`
	ArchivedAt                  pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid          pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                   bool               `json:"is_deleted"`
	DeletedAt                   pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid           pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type PropertyBlock struct {
	PropertyBlockUuid              pgtype.UUID        `json:"property_block_uuid"`
	TenantUuid                     pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid                  pgtype.UUID        `json:"workspace_uuid"`
	PropertyBlockTypeUniversalUuid pgtype.UUID        `json:"property_block_type_universal_uuid"`
	PropertyBlockName              string             `json:"property_block_name"`
	PropertyBlockCode              pgtype.Text        `json:"property_block_code"`
	ReraNumber                     pgtype.Text        `json:"rera_number"`
	NumberOfFloors                 pgtype.Int4        `json:"number_of_floors"`
	Remarks                        pgtype.Text        `json:"remarks"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid              pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                      pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid              pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                     bool               `json:"is_archived"`
	ArchivedAt                     pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid             pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                      bool               `json:"is_deleted"`
	DeletedAt                      pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid              pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type PropertyBlockStageProgress struct {
	PropertyBlockStageProgressUuid   pgtype.UUID        `json:"property_block_stage_progress_uuid"`
	TenantUuid                       pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid                    pgtype.UUID        `json:"workspace_uuid"`
	PropertyBlockUuid                pgtype.UUID        `json:"property_block_uuid"`
	ConstructionStageUniversalUuid   pgtype.UUID        `json:"construction_stage_universal_uuid"`
	CompletionDate                   pgtype.Date        `json:"completion_date"`
	ArchitectCertificateDocumentUuid pgtype.UUID        `json:"architect_certificate_document_uuid"`
	Remarks                          pgtype.Text        `json:"remarks"`
	CreatedAt                        pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid                pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                        pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid                pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                       bool               `json:"is_archived"`
	ArchivedAt                       pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid               pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                        bool               `json:"is_deleted"`
	DeletedAt                        pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid                pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type PropertyTransaction struct {
	PropertyTransactionUuid pgtype.UUID        `json:"property_transaction_uuid"`
	TenantUuid              pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid           pgtype.UUID        `json:"workspace_uuid"`
	PropertyUuid            pgtype.UUID        `json:"property_uuid"`
	OpportunityUuid         pgtype.UUID        `json:"opportunity_uuid"`
	QuotationUuid           pgtype.UUID        `json:"quotation_uuid"`
	ContactUuid             pgtype.UUID        `json:"contact_uuid"`
	StatusUuid              pgtype.UUID        `json:"status_uuid"`
	TransactionNumber       string             `json:"transaction_number"`
	TransactionType         string             `json:"transaction_type"`
	TransactionDate         pgtype.Date        `json:"transaction_date"`
	DealAmount              pgtype.Numeric     `json:"deal_amount"`
	MonthlyRent             pgtype.Numeric     `json:"monthly_rent"`
	DepositAmount           pgtype.Numeric     `json:"deposit_amount"`
	BrokerageAmount         pgtype.Numeric     `json:"brokerage_amount"`
	BrokerageReceivedAmount pgtype.Numeric     `json:"brokerage_received_amount"`
	BrokerageBalanceAmount  pgtype.Numeric     `json:"brokerage_balance_amount"`
	AgreementDate           pgtype.Date        `json:"agreement_date"`
	PossessionDate          pgtype.Date        `json:"possession_date"`
	Remarks                 pgtype.Text        `json:"remarks"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid       pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid       pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived              bool               `json:"is_archived"`
	ArchivedAt              pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid      pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted               bool               `json:"is_deleted"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid       pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Quotation struct {
	QuotationUuid      pgtype.UUID        `json:"quotation_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid      pgtype.UUID        `json:"workspace_uuid"`
	OpportunityUuid    pgtype.UUID        `json:"opportunity_uuid"`
	ContactUuid        pgtype.UUID        `json:"contact_uuid"`
	StatusUuid         pgtype.UUID        `json:"status_uuid"`
	QuotationNumber    string             `json:"quotation_number"`
	QuotationDate      pgtype.Date        `json:"quotation_date"`
	ValidUntil         pgtype.Date        `json:"valid_until"`
	UnitUuid           pgtype.UUID        `json:"unit_uuid"`
	PropertyUuid       pgtype.UUID        `json:"property_uuid"`
	TotalAmount        pgtype.Numeric     `json:"total_amount"`
	DiscountAmount     pgtype.Numeric     `json:"discount_amount"`
	FinalAmount        pgtype.Numeric     `json:"final_amount"`
	QuotationSnapshot  pgtype.Text        `json:"quotation_snapshot"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type QuotationCharge struct {
	QuotationChargeUuid     pgtype.UUID        `json:"quotation_charge_uuid"`
	TenantUuid              pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid           pgtype.UUID        `json:"workspace_uuid"`
	QuotationUuid           pgtype.UUID        `json:"quotation_uuid"`
	ChargeTypeUniversalUuid pgtype.UUID        `json:"charge_type_universal_uuid"`
	ChargeAmount            pgtype.Numeric     `json:"charge_amount"`
	Remarks                 pgtype.Text        `json:"remarks"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid       pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid       pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived              bool               `json:"is_archived"`
	ArchivedAt              pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid      pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted               bool               `json:"is_deleted"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid       pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type QuotationDiscount struct {
	QuotationDiscountUuid     pgtype.UUID        `json:"quotation_discount_uuid"`
	TenantUuid                pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid             pgtype.UUID        `json:"workspace_uuid"`
	QuotationUuid             pgtype.UUID        `json:"quotation_uuid"`
	DiscountTypeUniversalUuid pgtype.UUID        `json:"discount_type_universal_uuid"`
	DiscountValue             pgtype.Numeric     `json:"discount_value"`
	Remarks                   pgtype.Text        `json:"remarks"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid         pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid         pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                bool               `json:"is_archived"`
	ArchivedAt                pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid        pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                 bool               `json:"is_deleted"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid         pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Role struct {
	RoleUuid           pgtype.UUID        `json:"role_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	RoleName           string             `json:"role_name"`
	SortOrder          int32              `json:"sort_order"`
	IsSystem           bool               `json:"is_system"`
	IsActive           bool               `json:"is_active"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type RolePermission struct {
	RolePermissionUuid pgtype.UUID        `json:"role_permission_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	RoleUuid           pgtype.UUID        `json:"role_uuid"`
	ModuleUuid         pgtype.UUID        `json:"module_uuid"`
	PermissionUuid     pgtype.UUID        `json:"permission_uuid"`
	IsGranted          bool               `json:"is_granted"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type SavedFilter struct {
	SavedFilterUuid    pgtype.UUID        `json:"saved_filter_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid      pgtype.UUID        `json:"workspace_uuid"`
	ModuleUuid         pgtype.UUID        `json:"module_uuid"`
	UserUuid           pgtype.UUID        `json:"user_uuid"`
	FilterName         string             `json:"filter_name"`
	FilterJson         []byte             `json:"filter_json"`
	IsShared           bool               `json:"is_shared"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type SharedContentLog struct {
	SharedContentLogUuid pgtype.UUID        `json:"shared_content_log_uuid"`
	TenantUuid           pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid        pgtype.UUID        `json:"workspace_uuid"`
	ModuleUuid           pgtype.UUID        `json:"module_uuid"`
	EntityUuid           pgtype.UUID        `json:"entity_uuid"`
	ActivityUuid         pgtype.UUID        `json:"activity_uuid"`
	MessageQueueUuid     pgtype.UUID        `json:"message_queue_uuid"`
	MessageLogUuid       pgtype.UUID        `json:"message_log_uuid"`
	DocumentUuid         pgtype.UUID        `json:"document_uuid"`
	SharedUrl            pgtype.Text        `json:"shared_url"`
	SharedTitle          pgtype.Text        `json:"shared_title"`
	Recipient            pgtype.Text        `json:"recipient"`
	Remarks              pgtype.Text        `json:"remarks"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid    pgtype.UUID        `json:"created_by_user_uuid"`
	IsDeleted            bool               `json:"is_deleted"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid    pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type SiteVisit struct {
	SiteVisitUuid              pgtype.UUID        `json:"site_visit_uuid"`
	TenantUuid                 pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid              pgtype.UUID        `json:"workspace_uuid"`
	OpportunityUuid            pgtype.UUID        `json:"opportunity_uuid"`
	ActivityUuid               pgtype.UUID        `json:"activity_uuid"`
	AssignedUserUuid           pgtype.UUID        `json:"assigned_user_uuid"`
	PlannedVisitDatetime       pgtype.Timestamptz `json:"planned_visit_datetime"`
	ActualCheckinDatetime      pgtype.Timestamptz `json:"actual_checkin_datetime"`
	ActualCheckoutDatetime     pgtype.Timestamptz `json:"actual_checkout_datetime"`
	RescheduleReason           pgtype.Text        `json:"reschedule_reason"`
	FeedbackLink               pgtype.Text        `json:"feedback_link"`
	Rating                     pgtype.Numeric     `json:"rating"`
	AccompanyingMembersDetails []byte             `json:"accompanying_members_details"`
	Remarks                    pgtype.Text        `json:"remarks"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid          pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid          pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived                 bool               `json:"is_archived"`
	ArchivedAt                 pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid         pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                  bool               `json:"is_deleted"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid          pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Storage struct {
	StorageUuid        pgtype.UUID        `json:"storage_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid      pgtype.UUID        `json:"workspace_uuid"`
	PropertyBlockUuid  pgtype.UUID        `json:"property_block_uuid"`
	StorageNumber      string             `json:"storage_number"`
	IsBooked           bool               `json:"is_booked"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type SupportTicket struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Subject              string             `json:"subject"`
	Description          string             `json:"description"`
	Status               string             `json:"status"`
	Priority             string             `json:"priority"`
	ReopenCount          pgtype.Int4        `json:"reopen_count"`
	CustomerSatisfaction pgtype.Text        `json:"customer_satisfaction"`
	Rating               pgtype.Int4        `json:"rating"`
	AssignedTo           pgtype.UUID        `json:"assigned_to"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	TagUuid            pgtype.UUID        `json:"tag_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid      pgtype.UUID        `json:"workspace_uuid"`
	ModuleUuid         pgtype.UUID        `json:"module_uuid"`
	TagName            string             `json:"tag_name"`
	IsSystem           bool               `json:"is_system"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type TagAssigned struct {
	TagAssignedUuid    pgtype.UUID        `json:"tag_assigned_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid      pgtype.UUID        `json:"workspace_uuid"`
	ModuleUuid         pgtype.UUID        `json:"module_uuid"`
	EntityUuid         pgtype.UUID        `json:"entity_uuid"`
	TagUuid            pgtype.UUID        `json:"tag_uuid"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Tenant struct {
	TenantUuid                pgtype.UUID        `json:"tenant_uuid"`
	TenantCode                string             `json:"tenant_code"`
	TenantID                  string             `json:"tenant_id"`
	TenantName                string             `json:"tenant_name"`
	PlanTypeUniversalUuid     pgtype.UUID        `json:"plan_type_universal_uuid"`
	TenantStatusUniversalUuid pgtype.UUID        `json:"tenant_status_universal_uuid"`
	ContactPersonName         pgtype.Text        `json:"contact_person_name"`
	MobileNumber              pgtype.Text        `json:"mobile_number"`
	EmailAddress              pgtype.Text        `json:"email_address"`
	CountryName               pgtype.Text        `json:"country_name"`
	StateName                 pgtype.Text        `json:"state_name"`
	CityName                  pgtype.Text        `json:"city_name"`
	Address                   pgtype.Text        `json:"address"`
	GstNumber                 pgtype.Text        `json:"gst_number"`
	Remarks                   pgtype.Text        `json:"remarks"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid         pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid         pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt                pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid        pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                 bool               `json:"is_deleted"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid         pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type TenantAddonPurchase struct {
	TenantAddonPurchaseUuid pgtype.UUID        `json:"tenant_addon_purchase_uuid"`
	TenantUuid              pgtype.UUID        `json:"tenant_uuid"`
	AddonTypeUniversalUuid  pgtype.UUID        `json:"addon_type_universal_uuid"`
	Quantity                pgtype.Numeric     `json:"quantity"`
	PurchaseDate            pgtype.Date        `json:"purchase_date"`
	ExpiryDate              pgtype.Date        `json:"expiry_date"`
	Remarks                 pgtype.Text        `json:"remarks"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid       pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid       pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt              pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid      pgtype.UUID        `json:"archived_by_user_uuid"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid       pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type TenantNumberSeries struct {
	TenantNumberSeriesUuid pgtype.UUID        `json:"tenant_number_series_uuid"`
	TenantUuid             pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid          pgtype.UUID        `json:"workspace_uuid"`
	ModuleUuid             pgtype.UUID        `json:"module_uuid"`
	Prefix                 string             `json:"prefix"`
	PrefixSeparator        pgtype.Text        `json:"prefix_separator"`
	CurrentNumber          int64              `json:"current_number"`
	NumberPadding          int32              `json:"number_padding"`
	ResetType              int32              `json:"reset_type"`
	IsActive               bool               `json:"is_active"`
	Remarks                pgtype.Text        `json:"remarks"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid      pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid      pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt             pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid     pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted              bool               `json:"is_deleted"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid      pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type TenantSetting struct {
	TenantSettingUuid  pgtype.UUID        `json:"tenant_setting_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	CurrencyUuid       pgtype.UUID        `json:"currency_uuid"`
	TimezoneName       pgtype.Text        `json:"timezone_name"`
	DateFormat         pgtype.Text        `json:"date_format"`
	DefaultCountryName pgtype.Text        `json:"default_country_name"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type TenantSubscription struct {
	TenantSubscriptionUuid    pgtype.UUID        `json:"tenant_subscription_uuid"`
	SubscriptionNumber        string             `json:"subscription_number"`
	TenantUuid                pgtype.UUID        `json:"tenant_uuid"`
	PlanPriceUuid             pgtype.UUID        `json:"plan_price_uuid"`
	RenewalOfSubscriptionUuid pgtype.UUID        `json:"renewal_of_subscription_uuid"`
	SubscriptionStartDate     pgtype.Date        `json:"subscription_start_date"`
	SubscriptionEndDate       pgtype.Date        `json:"subscription_end_date"`
	GraceEndDate              pgtype.Date        `json:"grace_end_date"`
	AmountPaid                pgtype.Numeric     `json:"amount_paid"`
	Remarks                   pgtype.Text        `json:"remarks"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid         pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid         pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt                pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid        pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                 bool               `json:"is_deleted"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid         pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type TenantSubscriptionPayment struct {
	TenantSubscriptionPaymentUuid pgtype.UUID        `json:"tenant_subscription_payment_uuid"`
	PaymentNumber                 string             `json:"payment_number"`
	TenantUuid                    pgtype.UUID        `json:"tenant_uuid"`
	TenantSubscriptionUuid        pgtype.UUID        `json:"tenant_subscription_uuid"`
	PaymentModeUniversalUuid      pgtype.UUID        `json:"payment_mode_universal_uuid"`
	PaymentStatusUniversalUuid    pgtype.UUID        `json:"payment_status_universal_uuid"`
	PaymentDate                   pgtype.Date        `json:"payment_date"`
	Amount                        pgtype.Numeric     `json:"amount"`
	ReferenceNumber               pgtype.Text        `json:"reference_number"`
	ReceiptFileName               pgtype.Text        `json:"receipt_file_name"`
	Remarks                       pgtype.Text        `json:"remarks"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid             pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid             pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt                    pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid            pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                     bool               `json:"is_deleted"`
	DeletedAt                     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid             pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type TenantUsageLedger struct {
	TenantUsageLedgerUuid             pgtype.UUID        `json:"tenant_usage_ledger_uuid"`
	TenantUuid                        pgtype.UUID        `json:"tenant_uuid"`
	AddonTypeUniversalUuid            pgtype.UUID        `json:"addon_type_universal_uuid"`
	UsageTransactionTypeUniversalUuid pgtype.UUID        `json:"usage_transaction_type_universal_uuid"`
	TransactionDate                   pgtype.Timestamptz `json:"transaction_date"`
	Quantity                          pgtype.Numeric     `json:"quantity"`
	ReferenceNumber                   pgtype.Text        `json:"reference_number"`
	Remarks                           pgtype.Text        `json:"remarks"`
	CreatedAt                         pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid                 pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                         pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid                 pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt                        pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid                pgtype.UUID        `json:"archived_by_user_uuid"`
	DeletedAt                         pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid                 pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type Unit struct {
	UnitUuid                pgtype.UUID        `json:"unit_uuid"`
	TenantUuid              pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid           pgtype.UUID        `json:"workspace_uuid"`
	PropertyBlockUuid       pgtype.UUID        `json:"property_block_uuid"`
	UnitStatusUniversalUuid pgtype.UUID        `json:"unit_status_universal_uuid"`
	UnitTypeUniversalUuid   pgtype.UUID        `json:"unit_type_universal_uuid"`
	UnitNumber              string             `json:"unit_number"`
	FloorNumber             pgtype.Int4        `json:"floor_number"`
	CarpetArea              pgtype.Numeric     `json:"carpet_area"`
	BuiltupArea             pgtype.Numeric     `json:"builtup_area"`
	SaleableArea            pgtype.Numeric     `json:"saleable_area"`
	AreaUnitUniversalUuid   pgtype.UUID        `json:"area_unit_universal_uuid"`
	FacingDetails           []byte             `json:"facing_details"`
	AdditionalAreaDetails   []byte             `json:"additional_area_details"`
	BaseRate                pgtype.Numeric     `json:"base_rate"`
	AdditionalChargeDetails []byte             `json:"additional_charge_details"`
	Remarks                 pgtype.Text        `json:"remarks"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid       pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid       pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived              bool               `json:"is_archived"`
	ArchivedAt              pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid      pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted               bool               `json:"is_deleted"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid       pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type UnitHold struct {
	UnitHoldUuid       pgtype.UUID        `json:"unit_hold_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid      pgtype.UUID        `json:"workspace_uuid"`
	UnitUuid           pgtype.UUID        `json:"unit_uuid"`
	ContactUuid        pgtype.UUID        `json:"contact_uuid"`
	HeldByUserUuid     pgtype.UUID        `json:"held_by_user_uuid"`
	HoldFrom           pgtype.Timestamptz `json:"hold_from"`
	HoldUntil          pgtype.Timestamptz `json:"hold_until"`
	StatusUuid         pgtype.UUID        `json:"status_uuid"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	IsArchived         bool               `json:"is_archived"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type User struct {
	UserUuid                pgtype.UUID        `json:"user_uuid"`
	UserStatusUniversalUuid pgtype.UUID        `json:"user_status_universal_uuid"`
	FirstName               string             `json:"first_name"`
	LastName                pgtype.Text        `json:"last_name"`
	MobileNumber            pgtype.Text        `json:"mobile_number"`
	EmailAddress            pgtype.Text        `json:"email_address"`
	ProfilePhotoFileName    pgtype.Text        `json:"profile_photo_file_name"`
	Remarks                 pgtype.Text        `json:"remarks"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid       pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid       pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt              pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid      pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted               bool               `json:"is_deleted"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid       pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type UserAuth struct {
	UserAuthUuid          pgtype.UUID        `json:"user_auth_uuid"`
	TenantUuid            pgtype.UUID        `json:"tenant_uuid"`
	UserUuid              pgtype.UUID        `json:"user_uuid"`
	LoginID               string             `json:"login_id"`
	PasswordHash          string             `json:"password_hash"`
	IsMobileVerified      bool               `json:"is_mobile_verified"`
	IsEmailVerified       bool               `json:"is_email_verified"`
	LastPasswordChangedAt pgtype.Timestamptz `json:"last_password_changed_at"`
	LastLoginAt           pgtype.Timestamptz `json:"last_login_at"`
	FailedAttemptCount    int32              `json:"failed_attempt_count"`
	LockedUntil           pgtype.Timestamptz `json:"locked_until"`
	Remarks               pgtype.Text        `json:"remarks"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid     pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid     pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt            pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid    pgtype.UUID        `json:"archived_by_user_uuid"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid     pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type UserDevice struct {
	UserDeviceUuid          pgtype.UUID        `json:"user_device_uuid"`
	TenantUuid              pgtype.UUID        `json:"tenant_uuid"`
	UserUuid                pgtype.UUID        `json:"user_uuid"`
	DeviceTypeUniversalUuid pgtype.UUID        `json:"device_type_universal_uuid"`
	DeviceUuid              string             `json:"device_uuid"`
	DeviceName              pgtype.Text        `json:"device_name"`
	AppVersion              pgtype.Text        `json:"app_version"`
	DeviceOsVersion         pgtype.Text        `json:"device_os_version"`
	FirebaseToken           pgtype.Text        `json:"firebase_token"`
	LastSeenAt              pgtype.Timestamptz `json:"last_seen_at"`
	Remarks                 pgtype.Text        `json:"remarks"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid       pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid       pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt              pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid      pgtype.UUID        `json:"archived_by_user_uuid"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid       pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type UserLoginHistory struct {
	UserLoginHistoryUuid     pgtype.UUID        `json:"user_login_history_uuid"`
	TenantUuid               pgtype.UUID        `json:"tenant_uuid"`
	UserUuid                 pgtype.UUID        `json:"user_uuid"`
	LoginSourceUniversalUuid pgtype.UUID        `json:"login_source_universal_uuid"`
	DeviceUuid               pgtype.UUID        `json:"device_uuid"`
	LoginDatetime            pgtype.Timestamptz `json:"login_datetime"`
	LoginResultUniversalUuid pgtype.UUID        `json:"login_result_universal_uuid"`
	IpAddress                pgtype.Text        `json:"ip_address"`
	Remarks                  pgtype.Text        `json:"remarks"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid        pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid        pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt               pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid       pgtype.UUID        `json:"archived_by_user_uuid"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid        pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type UserOtp struct {
	UserOtpUuid             pgtype.UUID        `json:"user_otp_uuid"`
	TenantUuid              pgtype.UUID        `json:"tenant_uuid"`
	UserUuid                pgtype.UUID        `json:"user_uuid"`
	OtpPurposeUniversalUuid pgtype.UUID        `json:"otp_purpose_universal_uuid"`
	MobileNumber            pgtype.Text        `json:"mobile_number"`
	EmailAddress            pgtype.Text        `json:"email_address"`
	OtpCode                 string             `json:"otp_code"`
	SentAt                  pgtype.Timestamptz `json:"sent_at"`
	AttemptCount            int32              `json:"attempt_count"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	VerifiedAt              pgtype.Timestamptz `json:"verified_at"`
	IsConsumed              bool               `json:"is_consumed"`
	Remarks                 pgtype.Text        `json:"remarks"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid       pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid       pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt              pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid      pgtype.UUID        `json:"archived_by_user_uuid"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid       pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type UserSession struct {
	UserSessionUuid          pgtype.UUID        `json:"user_session_uuid"`
	TenantUuid               pgtype.UUID        `json:"tenant_uuid"`
	UserUuid                 pgtype.UUID        `json:"user_uuid"`
	LoginSourceUniversalUuid pgtype.UUID        `json:"login_source_universal_uuid"`
	DeviceUuid               pgtype.UUID        `json:"device_uuid"`
	JwtID                    pgtype.Text        `json:"jwt_id"`
	LoginAt                  pgtype.Timestamptz `json:"login_at"`
	LogoutAt                 pgtype.Timestamptz `json:"logout_at"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	IpAddress                pgtype.Text        `json:"ip_address"`
	Remarks                  pgtype.Text        `json:"remarks"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid        pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid        pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt               pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid       pgtype.UUID        `json:"archived_by_user_uuid"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid        pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type UserTenant struct {
	UserTenantUuid     pgtype.UUID        `json:"user_tenant_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	UserUuid           pgtype.UUID        `json:"user_uuid"`
	EmployeeCode       pgtype.Text        `json:"employee_code"`
	Designation        pgtype.Text        `json:"designation"`
	ProfileDetails     []byte             `json:"profile_details"`
	JoiningDate        pgtype.Date        `json:"joining_date"`
	LeavingDate        pgtype.Date        `json:"leaving_date"`
	IsDefaultTenant    bool               `json:"is_default_tenant"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type UserWorkspace struct {
	UserWorkspaceUuid  pgtype.UUID        `json:"user_workspace_uuid"`
	TenantUuid         pgtype.UUID        `json:"tenant_uuid"`
	UserTenantUuid     pgtype.UUID        `json:"user_tenant_uuid"`
	WorkspaceUuid      pgtype.UUID        `json:"workspace_uuid"`
	RoleUuid           pgtype.UUID        `json:"role_uuid"`
	AssignedAt         pgtype.Timestamptz `json:"assigned_at"`
	IsDefaultWorkspace bool               `json:"is_default_workspace"`
	Remarks            pgtype.Text        `json:"remarks"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid  pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid  pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted          bool               `json:"is_deleted"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid  pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type WebhookLog struct {
	WebhookLogUuid      pgtype.UUID        `json:"webhook_log_uuid"`
	TenantUuid          pgtype.UUID        `json:"tenant_uuid"`
	SourceName          string             `json:"source_name"`
	EventName           string             `json:"event_name"`
	ExternalReference   pgtype.Text        `json:"external_reference"`
	RequestPayloadJson  []byte             `json:"request_payload_json"`
	ResponsePayloadJson []byte             `json:"response_payload_json"`
	ProcessedAt         pgtype.Timestamptz `json:"processed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	WorkspaceUuid        pgtype.UUID        `json:"workspace_uuid"`
	TenantUuid           pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceName        string             `json:"workspace_name"`
	WorkspaceCode        pgtype.Text        `json:"workspace_code"`
	WorkspacePrefix      pgtype.Text        `json:"workspace_prefix"`
	PublicSlug           pgtype.Text        `json:"public_slug"`
	MicrositeSettings    []byte             `json:"microsite_settings"`
	DefaultOwnerUserUuid pgtype.UUID        `json:"default_owner_user_uuid"`
	IsOpenWorkspace      bool               `json:"is_open_workspace"`
	Remarks              pgtype.Text        `json:"remarks"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid    pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid    pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid   pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted            bool               `json:"is_deleted"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid    pgtype.UUID        `json:"deleted_by_user_uuid"`
}

type WorkspaceAssignmentRule struct {
	WorkspaceAssignmentRuleUuid pgtype.UUID        `json:"workspace_assignment_rule_uuid"`
	TenantUuid                  pgtype.UUID        `json:"tenant_uuid"`
	WorkspaceUuid               pgtype.UUID        `json:"workspace_uuid"`
	AssignmentTypeUniversalUuid pgtype.UUID        `json:"assignment_type_universal_uuid"`
	DefaultRoleUuid             pgtype.UUID        `json:"default_role_uuid"`
	DefaultUserUuid             pgtype.UUID        `json:"default_user_uuid"`
	LastAssignedUserUuid        pgtype.UUID        `json:"last_assigned_user_uuid"`
	IsActive                    bool               `json:"is_active"`
	Remarks                     pgtype.Text        `json:"remarks"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid           pgtype.UUID        `json:"created_by_user_uuid"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid           pgtype.UUID        `json:"updated_by_user_uuid"`
	ArchivedAt                  pgtype.Timestamptz `json:"archived_at"`
	ArchivedByUserUuid          pgtype.UUID        `json:"archived_by_user_uuid"`
	IsDeleted                   bool               `json:"is_deleted"`
	DeletedAt                   pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid           pgtype.UUID        `json:"deleted_by_user_uuid"`
}
