// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO tenant_subscription_payment (
    tenant_subscription_payment_uuid,
    payment_number,
    tenant_uuid,
    tenant_subscription_uuid,
    payment_status_universal_uuid,
    payment_mode_universal_uuid,
    payment_date,
    amount,
    remarks,
    created_at,
    created_by_user_uuid
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING tenant_subscription_payment_uuid, payment_number, tenant_uuid, tenant_subscription_uuid, payment_mode_universal_uuid, payment_status_universal_uuid, payment_date, amount, reference_number, receipt_file_name, remarks, created_at, created_by_user_uuid, updated_at, updated_by_user_uuid, archived_at, archived_by_user_uuid, is_deleted, deleted_at, deleted_by_user_uuid
`

type CreatePaymentParams struct {
	TenantSubscriptionPaymentUuid pgtype.UUID        `json:"tenant_subscription_payment_uuid"`
	PaymentNumber                 string             `json:"payment_number"`
	TenantUuid                    pgtype.UUID        `json:"tenant_uuid"`
	TenantSubscriptionUuid        pgtype.UUID        `json:"tenant_subscription_uuid"`
	PaymentStatusUniversalUuid    pgtype.UUID        `json:"payment_status_universal_uuid"`
	PaymentModeUniversalUuid      pgtype.UUID        `json:"payment_mode_universal_uuid"`
	PaymentDate                   pgtype.Date        `json:"payment_date"`
	Amount                        pgtype.Numeric     `json:"amount"`
	Remarks                       pgtype.Text        `json:"remarks"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid             pgtype.UUID        `json:"created_by_user_uuid"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (TenantSubscriptionPayment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.TenantSubscriptionPaymentUuid,
		arg.PaymentNumber,
		arg.TenantUuid,
		arg.TenantSubscriptionUuid,
		arg.PaymentStatusUniversalUuid,
		arg.PaymentModeUniversalUuid,
		arg.PaymentDate,
		arg.Amount,
		arg.Remarks,
		arg.CreatedAt,
		arg.CreatedByUserUuid,
	)
	var i TenantSubscriptionPayment
	err := row.Scan(
		&i.TenantSubscriptionPaymentUuid,
		&i.PaymentNumber,
		&i.TenantUuid,
		&i.TenantSubscriptionUuid,
		&i.PaymentModeUniversalUuid,
		&i.PaymentStatusUniversalUuid,
		&i.PaymentDate,
		&i.Amount,
		&i.ReferenceNumber,
		&i.ReceiptFileName,
		&i.Remarks,
		&i.CreatedAt,
		&i.CreatedByUserUuid,
		&i.UpdatedAt,
		&i.UpdatedByUserUuid,
		&i.ArchivedAt,
		&i.ArchivedByUserUuid,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedByUserUuid,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :exec
UPDATE tenant_subscription_payment
SET
    is_deleted = true,
    deleted_at = $2,
    deleted_by_user_uuid = $3
WHERE tenant_subscription_payment_uuid = $1
`

type DeletePaymentParams struct {
	TenantSubscriptionPaymentUuid pgtype.UUID        `json:"tenant_subscription_payment_uuid"`
	DeletedAt                     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserUuid             pgtype.UUID        `json:"deleted_by_user_uuid"`
}

func (q *Queries) DeletePayment(ctx context.Context, arg DeletePaymentParams) error {
	_, err := q.db.Exec(ctx, deletePayment, arg.TenantSubscriptionPaymentUuid, arg.DeletedAt, arg.DeletedByUserUuid)
	return err
}

const getPayment = `-- name: GetPayment :one
SELECT tenant_subscription_payment_uuid, payment_number, tenant_uuid, tenant_subscription_uuid, payment_mode_universal_uuid, payment_status_universal_uuid, payment_date, amount, reference_number, receipt_file_name, remarks, created_at, created_by_user_uuid, updated_at, updated_by_user_uuid, archived_at, archived_by_user_uuid, is_deleted, deleted_at, deleted_by_user_uuid FROM tenant_subscription_payment
WHERE tenant_subscription_payment_uuid = $1 AND is_deleted = false
`

func (q *Queries) GetPayment(ctx context.Context, tenantSubscriptionPaymentUuid pgtype.UUID) (TenantSubscriptionPayment, error) {
	row := q.db.QueryRow(ctx, getPayment, tenantSubscriptionPaymentUuid)
	var i TenantSubscriptionPayment
	err := row.Scan(
		&i.TenantSubscriptionPaymentUuid,
		&i.PaymentNumber,
		&i.TenantUuid,
		&i.TenantSubscriptionUuid,
		&i.PaymentModeUniversalUuid,
		&i.PaymentStatusUniversalUuid,
		&i.PaymentDate,
		&i.Amount,
		&i.ReferenceNumber,
		&i.ReceiptFileName,
		&i.Remarks,
		&i.CreatedAt,
		&i.CreatedByUserUuid,
		&i.UpdatedAt,
		&i.UpdatedByUserUuid,
		&i.ArchivedAt,
		&i.ArchivedByUserUuid,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedByUserUuid,
	)
	return i, err
}

const getPaymentStats = `-- name: GetPaymentStats :one
SELECT 
    COUNT(*) AS total_payments,
    COALESCE(SUM(amount) FILTER (WHERE u_status.value_name = 'Paid'), 0) AS total_received,
    COALESCE(SUM(amount) FILTER (WHERE u_status.value_name = 'Pending'), 0) AS pending_amount,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Pending') AS pending_count,
    COALESCE(SUM(amount) FILTER (WHERE u_status.value_name = 'Failed'), 0) AS failed_amount,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Failed') AS failed_count,
    COALESCE(SUM(amount) FILTER (WHERE u_status.value_name = 'Refunded'), 0) AS refunded_amount,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Refunded') AS refunded_count
FROM tenant_subscription_payment p
LEFT JOIN mst_universal u_status ON p.payment_status_universal_uuid = u_status.universal_uuid
WHERE p.is_deleted = false
`

type GetPaymentStatsRow struct {
	TotalPayments  int64       `json:"total_payments"`
	TotalReceived  interface{} `json:"total_received"`
	PendingAmount  interface{} `json:"pending_amount"`
	PendingCount   int64       `json:"pending_count"`
	FailedAmount   interface{} `json:"failed_amount"`
	FailedCount    int64       `json:"failed_count"`
	RefundedAmount interface{} `json:"refunded_amount"`
	RefundedCount  int64       `json:"refunded_count"`
}

func (q *Queries) GetPaymentStats(ctx context.Context) (GetPaymentStatsRow, error) {
	row := q.db.QueryRow(ctx, getPaymentStats)
	var i GetPaymentStatsRow
	err := row.Scan(
		&i.TotalPayments,
		&i.TotalReceived,
		&i.PendingAmount,
		&i.PendingCount,
		&i.FailedAmount,
		&i.FailedCount,
		&i.RefundedAmount,
		&i.RefundedCount,
	)
	return i, err
}

const listPaymentsPaginated = `-- name: ListPaymentsPaginated :many
SELECT 
    p.tenant_subscription_payment_uuid,
    p.payment_number AS transaction_id,
    t.tenant_name AS customer,
    t.email_address,
    COALESCE(u_status.value_name, 'Unknown') AS status,
    COALESCE(pl.plan_name, 'None') AS plan,
    p.amount,
    COALESCE(u_mode.value_name, 'Unknown') AS method,
    p.payment_date,
    COUNT(*) OVER() AS total_records
FROM tenant_subscription_payment p
JOIN tenant t ON p.tenant_uuid = t.tenant_uuid
LEFT JOIN tenant_subscription ts ON p.tenant_subscription_uuid = ts.tenant_subscription_uuid
LEFT JOIN mst_plan_price pp ON ts.plan_price_uuid = pp.plan_price_uuid
LEFT JOIN mst_plan pl ON pp.plan_uuid = pl.plan_uuid
LEFT JOIN mst_universal u_status ON p.payment_status_universal_uuid = u_status.universal_uuid
LEFT JOIN mst_universal u_mode ON p.payment_mode_universal_uuid = u_mode.universal_uuid
WHERE 
    p.is_deleted = false
    AND ($1::text = '' OR p.payment_number ILIKE '%' || $1 || '%' OR t.tenant_name ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR u_status.value_name = $2)
    AND ($3::text = '' OR u_mode.value_name = $3)
    AND ($4::text = '' OR pl.plan_name = $4)
    AND (
        ($7::text = '' OR $8::text = '') 
        OR 
        (p.payment_date >= $7::date AND p.payment_date <= $8::date)
    )
ORDER BY p.payment_date DESC, p.created_at DESC
LIMIT $6 OFFSET $5
`

type ListPaymentsPaginatedParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Offset  int32  `json:"offset"`
	Limit   int32  `json:"limit"`
	Column7 string `json:"column_7"`
	Column8 string `json:"column_8"`
}

type ListPaymentsPaginatedRow struct {
	TenantSubscriptionPaymentUuid pgtype.UUID    `json:"tenant_subscription_payment_uuid"`
	TransactionID                 string         `json:"transaction_id"`
	Customer                      string         `json:"customer"`
	EmailAddress                  pgtype.Text    `json:"email_address"`
	Status                        string         `json:"status"`
	Plan                          string         `json:"plan"`
	Amount                        pgtype.Numeric `json:"amount"`
	Method                        string         `json:"method"`
	PaymentDate                   pgtype.Date    `json:"payment_date"`
	TotalRecords                  int64          `json:"total_records"`
}

func (q *Queries) ListPaymentsPaginated(ctx context.Context, arg ListPaymentsPaginatedParams) ([]ListPaymentsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsPaginated,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Offset,
		arg.Limit,
		arg.Column7,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsPaginatedRow
	for rows.Next() {
		var i ListPaymentsPaginatedRow
		if err := rows.Scan(
			&i.TenantSubscriptionPaymentUuid,
			&i.TransactionID,
			&i.Customer,
			&i.EmailAddress,
			&i.Status,
			&i.Plan,
			&i.Amount,
			&i.Method,
			&i.PaymentDate,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE tenant_subscription_payment
SET
    payment_status_universal_uuid = COALESCE($2, payment_status_universal_uuid),
    payment_mode_universal_uuid = COALESCE($3, payment_mode_universal_uuid),
    payment_date = COALESCE($4, payment_date),
    amount = COALESCE($5, amount),
    remarks = COALESCE($6, remarks),
    updated_at = $7,
    updated_by_user_uuid = $8
WHERE tenant_subscription_payment_uuid = $1 AND is_deleted = false
RETURNING tenant_subscription_payment_uuid, payment_number, tenant_uuid, tenant_subscription_uuid, payment_mode_universal_uuid, payment_status_universal_uuid, payment_date, amount, reference_number, receipt_file_name, remarks, created_at, created_by_user_uuid, updated_at, updated_by_user_uuid, archived_at, archived_by_user_uuid, is_deleted, deleted_at, deleted_by_user_uuid
`

type UpdatePaymentParams struct {
	TenantSubscriptionPaymentUuid pgtype.UUID        `json:"tenant_subscription_payment_uuid"`
	PaymentStatusUniversalUuid    pgtype.UUID        `json:"payment_status_universal_uuid"`
	PaymentModeUniversalUuid      pgtype.UUID        `json:"payment_mode_universal_uuid"`
	PaymentDate                   pgtype.Date        `json:"payment_date"`
	Amount                        pgtype.Numeric     `json:"amount"`
	Remarks                       pgtype.Text        `json:"remarks"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserUuid             pgtype.UUID        `json:"updated_by_user_uuid"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (TenantSubscriptionPayment, error) {
	row := q.db.QueryRow(ctx, updatePayment,
		arg.TenantSubscriptionPaymentUuid,
		arg.PaymentStatusUniversalUuid,
		arg.PaymentModeUniversalUuid,
		arg.PaymentDate,
		arg.Amount,
		arg.Remarks,
		arg.UpdatedAt,
		arg.UpdatedByUserUuid,
	)
	var i TenantSubscriptionPayment
	err := row.Scan(
		&i.TenantSubscriptionPaymentUuid,
		&i.PaymentNumber,
		&i.TenantUuid,
		&i.TenantSubscriptionUuid,
		&i.PaymentModeUniversalUuid,
		&i.PaymentStatusUniversalUuid,
		&i.PaymentDate,
		&i.Amount,
		&i.ReferenceNumber,
		&i.ReceiptFileName,
		&i.Remarks,
		&i.CreatedAt,
		&i.CreatedByUserUuid,
		&i.UpdatedAt,
		&i.UpdatedByUserUuid,
		&i.ArchivedAt,
		&i.ArchivedByUserUuid,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedByUserUuid,
	)
	return i, err
}
