// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMstPlan = `-- name: CreateMstPlan :exec
INSERT INTO mst_plan (
    plan_uuid, plan_name, remarks, max_users, default_storage_bytes, default_sms_credits, default_whatsapp_credits, default_email_credits, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, now(), now()
)
`

type CreateMstPlanParams struct {
	PlanUuid               pgtype.UUID `json:"plan_uuid"`
	PlanName               string      `json:"plan_name"`
	Remarks                pgtype.Text `json:"remarks"`
	MaxUsers               int32       `json:"max_users"`
	DefaultStorageBytes    int64       `json:"default_storage_bytes"`
	DefaultSmsCredits      int32       `json:"default_sms_credits"`
	DefaultWhatsappCredits int32       `json:"default_whatsapp_credits"`
	DefaultEmailCredits    int32       `json:"default_email_credits"`
}

func (q *Queries) CreateMstPlan(ctx context.Context, arg CreateMstPlanParams) error {
	_, err := q.db.Exec(ctx, createMstPlan,
		arg.PlanUuid,
		arg.PlanName,
		arg.Remarks,
		arg.MaxUsers,
		arg.DefaultStorageBytes,
		arg.DefaultSmsCredits,
		arg.DefaultWhatsappCredits,
		arg.DefaultEmailCredits,
	)
	return err
}

const createMstPlanPrice = `-- name: CreateMstPlanPrice :exec
INSERT INTO mst_plan_price (
    plan_price_uuid, plan_uuid, price_amount, created_at, updated_at
) VALUES (
    $1, $2, $3, now(), now()
)
`

type CreateMstPlanPriceParams struct {
	PlanPriceUuid pgtype.UUID    `json:"plan_price_uuid"`
	PlanUuid      pgtype.UUID    `json:"plan_uuid"`
	PriceAmount   pgtype.Numeric `json:"price_amount"`
}

func (q *Queries) CreateMstPlanPrice(ctx context.Context, arg CreateMstPlanPriceParams) error {
	_, err := q.db.Exec(ctx, createMstPlanPrice, arg.PlanPriceUuid, arg.PlanUuid, arg.PriceAmount)
	return err
}

const deleteMstPlan = `-- name: DeleteMstPlan :exec
DELETE FROM mst_plan
WHERE plan_uuid = $1
`

func (q *Queries) DeleteMstPlan(ctx context.Context, planUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMstPlan, planUuid)
	return err
}

const getFirstPlanPriceByPlan = `-- name: GetFirstPlanPriceByPlan :one
SELECT plan_price_uuid FROM mst_plan_price WHERE plan_uuid = $1 LIMIT 1
`

func (q *Queries) GetFirstPlanPriceByPlan(ctx context.Context, planUuid pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getFirstPlanPriceByPlan, planUuid)
	var plan_price_uuid pgtype.UUID
	err := row.Scan(&plan_price_uuid)
	return plan_price_uuid, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT p.plan_uuid as id, p.plan_name as name, COALESCE(mt.value_name, 'Unknown') as plan_type, p.remarks as description, pp.price_amount as price, COALESCE(mt_cycle.value_name, 'Monthly') as interval, p.max_users, p.default_storage_bytes, p.default_sms_credits, p.default_whatsapp_credits, p.default_email_credits, p.created_at, p.updated_at
FROM mst_plan p
LEFT JOIN mst_plan_price pp ON p.plan_uuid = pp.plan_uuid
LEFT JOIN mst_universal mt ON p.plan_type_universal_uuid = mt.universal_uuid
LEFT JOIN mst_universal mt_cycle ON pp.billing_cycle_universal_uuid = mt_cycle.universal_uuid
WHERE p.plan_uuid = $1
LIMIT 1
`

type GetPlanByIDRow struct {
	ID                     pgtype.UUID        `json:"id"`
	Name                   string             `json:"name"`
	PlanType               string             `json:"plan_type"`
	Description            pgtype.Text        `json:"description"`
	Price                  pgtype.Numeric     `json:"price"`
	Interval               string             `json:"interval"`
	MaxUsers               int32              `json:"max_users"`
	DefaultStorageBytes    int64              `json:"default_storage_bytes"`
	DefaultSmsCredits      int32              `json:"default_sms_credits"`
	DefaultWhatsappCredits int32              `json:"default_whatsapp_credits"`
	DefaultEmailCredits    int32              `json:"default_email_credits"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPlanByID(ctx context.Context, planUuid pgtype.UUID) (GetPlanByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlanByID, planUuid)
	var i GetPlanByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanType,
		&i.Description,
		&i.Price,
		&i.Interval,
		&i.MaxUsers,
		&i.DefaultStorageBytes,
		&i.DefaultSmsCredits,
		&i.DefaultWhatsappCredits,
		&i.DefaultEmailCredits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT p.plan_uuid as id, p.plan_name as name, COALESCE(mt.value_name, 'Unknown') as plan_type, p.remarks as description, pp.price_amount as price, COALESCE(mt_cycle.value_name, 'Monthly') as interval, p.max_users, p.default_storage_bytes, p.default_sms_credits, p.default_whatsapp_credits, p.default_email_credits, p.created_at, p.updated_at
FROM mst_plan p
LEFT JOIN mst_plan_price pp ON p.plan_uuid = pp.plan_uuid
LEFT JOIN mst_universal mt ON p.plan_type_universal_uuid = mt.universal_uuid
LEFT JOIN mst_universal mt_cycle ON pp.billing_cycle_universal_uuid = mt_cycle.universal_uuid
ORDER BY p.created_at DESC
`

type ListPlansRow struct {
	ID                     pgtype.UUID        `json:"id"`
	Name                   string             `json:"name"`
	PlanType               string             `json:"plan_type"`
	Description            pgtype.Text        `json:"description"`
	Price                  pgtype.Numeric     `json:"price"`
	Interval               string             `json:"interval"`
	MaxUsers               int32              `json:"max_users"`
	DefaultStorageBytes    int64              `json:"default_storage_bytes"`
	DefaultSmsCredits      int32              `json:"default_sms_credits"`
	DefaultWhatsappCredits int32              `json:"default_whatsapp_credits"`
	DefaultEmailCredits    int32              `json:"default_email_credits"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPlans(ctx context.Context) ([]ListPlansRow, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlansRow
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PlanType,
			&i.Description,
			&i.Price,
			&i.Interval,
			&i.MaxUsers,
			&i.DefaultStorageBytes,
			&i.DefaultSmsCredits,
			&i.DefaultWhatsappCredits,
			&i.DefaultEmailCredits,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMstPlan = `-- name: UpdateMstPlan :exec
UPDATE mst_plan
SET plan_name = $2, remarks = $3, max_users = $4, default_storage_bytes = $5, default_sms_credits = $6, default_whatsapp_credits = $7, default_email_credits = $8, updated_at = now()
WHERE plan_uuid = $1
`

type UpdateMstPlanParams struct {
	PlanUuid               pgtype.UUID `json:"plan_uuid"`
	PlanName               string      `json:"plan_name"`
	Remarks                pgtype.Text `json:"remarks"`
	MaxUsers               int32       `json:"max_users"`
	DefaultStorageBytes    int64       `json:"default_storage_bytes"`
	DefaultSmsCredits      int32       `json:"default_sms_credits"`
	DefaultWhatsappCredits int32       `json:"default_whatsapp_credits"`
	DefaultEmailCredits    int32       `json:"default_email_credits"`
}

func (q *Queries) UpdateMstPlan(ctx context.Context, arg UpdateMstPlanParams) error {
	_, err := q.db.Exec(ctx, updateMstPlan,
		arg.PlanUuid,
		arg.PlanName,
		arg.Remarks,
		arg.MaxUsers,
		arg.DefaultStorageBytes,
		arg.DefaultSmsCredits,
		arg.DefaultWhatsappCredits,
		arg.DefaultEmailCredits,
	)
	return err
}

const updateMstPlanPrice = `-- name: UpdateMstPlanPrice :exec
UPDATE mst_plan_price
SET price_amount = $2, updated_at = now()
WHERE plan_uuid = $1
`

type UpdateMstPlanPriceParams struct {
	PlanUuid    pgtype.UUID    `json:"plan_uuid"`
	PriceAmount pgtype.Numeric `json:"price_amount"`
}

func (q *Queries) UpdateMstPlanPrice(ctx context.Context, arg UpdateMstPlanPriceParams) error {
	_, err := q.db.Exec(ctx, updateMstPlanPrice, arg.PlanUuid, arg.PriceAmount)
	return err
}
