// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.permission_code, rp.role_permission_uuid FROM role_permission rp JOIN mst_permission p ON rp.permission_uuid = p.permission_uuid WHERE rp.role_uuid = $1 AND rp.is_deleted = FALSE AND p.deleted_at IS NULL
`

type GetRolePermissionsRow struct {
	PermissionCode     string      `json:"permission_code"`
	RolePermissionUuid pgtype.UUID `json:"role_permission_uuid"`
}

func (q *Queries) GetRolePermissions(ctx context.Context, roleUuid pgtype.UUID) ([]GetRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRolePermissionsRow
	for rows.Next() {
		var i GetRolePermissionsRow
		if err := rows.Scan(&i.PermissionCode, &i.RolePermissionUuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT r.role_uuid, r.role_name, r.remarks, (SELECT COUNT(DISTINCT uw.user_tenant_uuid) FROM user_workspace uw WHERE uw.role_uuid = r.role_uuid AND uw.is_deleted = FALSE) AS user_count FROM role r WHERE r.is_deleted = FALSE ORDER BY r.sort_order ASC, r.created_at DESC
`

type ListRolesRow struct {
	RoleUuid  pgtype.UUID `json:"role_uuid"`
	RoleName  string      `json:"role_name"`
	Remarks   pgtype.Text `json:"remarks"`
	UserCount int64       `json:"user_count"`
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.RoleUuid,
			&i.RoleName,
			&i.Remarks,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :exec
UPDATE role SET role_name = $2, remarks = $3, updated_at = NOW() WHERE role_uuid = $1 AND is_deleted = FALSE
`

type UpdateRoleParams struct {
	RoleUuid pgtype.UUID `json:"role_uuid"`
	RoleName string      `json:"role_name"`
	Remarks  pgtype.Text `json:"remarks"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole, arg.RoleUuid, arg.RoleName, arg.Remarks)
	return err
}
