// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE tenant_subscription
SET is_deleted = true, deleted_at = NOW()
WHERE subscription_number = $1
`

func (q *Queries) CancelSubscription(ctx context.Context, subscriptionNumber string) error {
	_, err := q.db.Exec(ctx, cancelSubscription, subscriptionNumber)
	return err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO tenant_subscription (
    tenant_subscription_uuid, 
    subscription_number, 
    tenant_uuid, 
    plan_price_uuid, 
    subscription_start_date, 
    subscription_end_date, 
    amount_paid,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
) RETURNING tenant_subscription_uuid
`

type CreateSubscriptionParams struct {
	TenantSubscriptionUuid pgtype.UUID    `json:"tenant_subscription_uuid"`
	SubscriptionNumber     string         `json:"subscription_number"`
	TenantUuid             pgtype.UUID    `json:"tenant_uuid"`
	PlanPriceUuid          pgtype.UUID    `json:"plan_price_uuid"`
	SubscriptionStartDate  pgtype.Date    `json:"subscription_start_date"`
	SubscriptionEndDate    pgtype.Date    `json:"subscription_end_date"`
	AmountPaid             pgtype.Numeric `json:"amount_paid"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.TenantSubscriptionUuid,
		arg.SubscriptionNumber,
		arg.TenantUuid,
		arg.PlanPriceUuid,
		arg.SubscriptionStartDate,
		arg.SubscriptionEndDate,
		arg.AmountPaid,
	)
	var tenant_subscription_uuid pgtype.UUID
	err := row.Scan(&tenant_subscription_uuid)
	return tenant_subscription_uuid, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT 
    t.tenant_name AS customer_name,
    t.email_address AS customer_email,
    ts.subscription_number,
    p.plan_name,
    u_type.value_name AS plan_type,
    u_cycle.value_name AS billing_cycle,
    u_status.value_name AS status,
    ts.subscription_start_date AS start_date,
    ts.subscription_end_date AS next_billing_date,
    pp.price_amount AS mrr,
    u_payment.value_name AS payment_status,
    COUNT(*) OVER() AS total_records
FROM tenant_subscription ts
JOIN tenant t ON ts.tenant_uuid = t.tenant_uuid
JOIN mst_plan_price pp ON ts.plan_price_uuid = pp.plan_price_uuid
JOIN mst_plan p ON pp.plan_uuid = p.plan_uuid
LEFT JOIN mst_universal u_type ON p.plan_type_universal_uuid = u_type.universal_uuid
LEFT JOIN mst_universal u_cycle ON pp.billing_cycle_universal_uuid = u_cycle.universal_uuid
LEFT JOIN tenant_subscription_payment tsp ON ts.tenant_subscription_uuid = tsp.tenant_subscription_uuid
LEFT JOIN mst_universal u_status ON t.tenant_status_universal_uuid = u_status.universal_uuid
LEFT JOIN mst_universal u_payment ON tsp.payment_status_universal_uuid = u_payment.universal_uuid
WHERE 
    ($1::text = '' OR t.tenant_name ILIKE '%' || $1 || '%' OR ts.subscription_number ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR u_status.value_name = $2)
    AND ($3::text = '' OR p.plan_name = $3)
    AND ($4::text = '' OR u_cycle.value_name = $4)
    AND ($5::text = '' OR u_payment.value_name = $5)
ORDER BY ts.created_at DESC
LIMIT $7
OFFSET $6
`

type ListSubscriptionsParams struct {
	SearchName    string `json:"search_name"`
	Status        string `json:"status"`
	PlanName      string `json:"plan_name"`
	BillingCycle  string `json:"billing_cycle"`
	PaymentStatus string `json:"payment_status"`
	Offset        int32  `json:"offset"`
	Limit         int32  `json:"limit"`
}

type ListSubscriptionsRow struct {
	CustomerName       string         `json:"customer_name"`
	CustomerEmail      pgtype.Text    `json:"customer_email"`
	SubscriptionNumber string         `json:"subscription_number"`
	PlanName           string         `json:"plan_name"`
	PlanType           pgtype.Text    `json:"plan_type"`
	BillingCycle       pgtype.Text    `json:"billing_cycle"`
	Status             pgtype.Text    `json:"status"`
	StartDate          pgtype.Date    `json:"start_date"`
	NextBillingDate    pgtype.Date    `json:"next_billing_date"`
	Mrr                pgtype.Numeric `json:"mrr"`
	PaymentStatus      pgtype.Text    `json:"payment_status"`
	TotalRecords       int64          `json:"total_records"`
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]ListSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptions,
		arg.SearchName,
		arg.Status,
		arg.PlanName,
		arg.BillingCycle,
		arg.PaymentStatus,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsRow
	for rows.Next() {
		var i ListSubscriptionsRow
		if err := rows.Scan(
			&i.CustomerName,
			&i.CustomerEmail,
			&i.SubscriptionNumber,
			&i.PlanName,
			&i.PlanType,
			&i.BillingCycle,
			&i.Status,
			&i.StartDate,
			&i.NextBillingDate,
			&i.Mrr,
			&i.PaymentStatus,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
