// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: support_tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSupportTicket = `-- name: CreateSupportTicket :one
INSERT INTO support_tickets (
    tenant_id, user_id, subject, description, priority
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, tenant_id, user_id, subject, description, status, priority, reopen_count, customer_satisfaction, rating, assigned_to, created_at, updated_at
`

type CreateSupportTicketParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Subject     string      `json:"subject"`
	Description string      `json:"description"`
	Priority    string      `json:"priority"`
}

func (q *Queries) CreateSupportTicket(ctx context.Context, arg CreateSupportTicketParams) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, createSupportTicket,
		arg.TenantID,
		arg.UserID,
		arg.Subject,
		arg.Description,
		arg.Priority,
	)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ReopenCount,
		&i.CustomerSatisfaction,
		&i.Rating,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupportTicket = `-- name: GetSupportTicket :one
SELECT id, tenant_id, user_id, subject, description, status, priority, reopen_count, customer_satisfaction, rating, assigned_to, created_at, updated_at FROM support_tickets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSupportTicket(ctx context.Context, id pgtype.UUID) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, getSupportTicket, id)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ReopenCount,
		&i.CustomerSatisfaction,
		&i.Rating,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClosedSupportTickets = `-- name: ListClosedSupportTickets :many
SELECT id, tenant_id, user_id, subject, description, status, priority, reopen_count, customer_satisfaction, rating, assigned_to, created_at, updated_at FROM support_tickets
WHERE status = 'Closed' OR status = 'Resolved'
ORDER BY created_at DESC
`

func (q *Queries) ListClosedSupportTickets(ctx context.Context) ([]SupportTicket, error) {
	rows, err := q.db.Query(ctx, listClosedSupportTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportTicket
	for rows.Next() {
		var i SupportTicket
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Subject,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ReopenCount,
			&i.CustomerSatisfaction,
			&i.Rating,
			&i.AssignedTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenSupportTickets = `-- name: ListOpenSupportTickets :many
SELECT id, tenant_id, user_id, subject, description, status, priority, reopen_count, customer_satisfaction, rating, assigned_to, created_at, updated_at FROM support_tickets
WHERE status = 'Open' OR status = 'In Progress'
ORDER BY created_at DESC
`

func (q *Queries) ListOpenSupportTickets(ctx context.Context) ([]SupportTicket, error) {
	rows, err := q.db.Query(ctx, listOpenSupportTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportTicket
	for rows.Next() {
		var i SupportTicket
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Subject,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ReopenCount,
			&i.CustomerSatisfaction,
			&i.Rating,
			&i.AssignedTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rateSupportTicket = `-- name: RateSupportTicket :one
UPDATE support_tickets
SET customer_satisfaction = $2,
    rating = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, tenant_id, user_id, subject, description, status, priority, reopen_count, customer_satisfaction, rating, assigned_to, created_at, updated_at
`

type RateSupportTicketParams struct {
	ID                   pgtype.UUID `json:"id"`
	CustomerSatisfaction pgtype.Text `json:"customer_satisfaction"`
	Rating               pgtype.Int4 `json:"rating"`
}

func (q *Queries) RateSupportTicket(ctx context.Context, arg RateSupportTicketParams) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, rateSupportTicket, arg.ID, arg.CustomerSatisfaction, arg.Rating)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ReopenCount,
		&i.CustomerSatisfaction,
		&i.Rating,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reopenSupportTicket = `-- name: ReopenSupportTicket :one
UPDATE support_tickets
SET status = 'Open', 
    reopen_count = reopen_count + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, tenant_id, user_id, subject, description, status, priority, reopen_count, customer_satisfaction, rating, assigned_to, created_at, updated_at
`

func (q *Queries) ReopenSupportTicket(ctx context.Context, id pgtype.UUID) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, reopenSupportTicket, id)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ReopenCount,
		&i.CustomerSatisfaction,
		&i.Rating,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSupportTicketStatus = `-- name: UpdateSupportTicketStatus :one
UPDATE support_tickets
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, tenant_id, user_id, subject, description, status, priority, reopen_count, customer_satisfaction, rating, assigned_to, created_at, updated_at
`

type UpdateSupportTicketStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateSupportTicketStatus(ctx context.Context, arg UpdateSupportTicketStatusParams) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, updateSupportTicketStatus, arg.ID, arg.Status)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ReopenCount,
		&i.CustomerSatisfaction,
		&i.Rating,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
