// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenant (
    tenant_uuid, tenant_code, tenant_id, tenant_name, email_address,
    contact_person_name, mobile_number, country_name, state_name, city_name, address, gst_number, remarks,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, now(), now()
)
`

type CreateTenantParams struct {
	TenantUuid        pgtype.UUID `json:"tenant_uuid"`
	TenantCode        string      `json:"tenant_code"`
	TenantID          string      `json:"tenant_id"`
	TenantName        string      `json:"tenant_name"`
	EmailAddress      pgtype.Text `json:"email_address"`
	ContactPersonName pgtype.Text `json:"contact_person_name"`
	MobileNumber      pgtype.Text `json:"mobile_number"`
	CountryName       pgtype.Text `json:"country_name"`
	StateName         pgtype.Text `json:"state_name"`
	CityName          pgtype.Text `json:"city_name"`
	Address           pgtype.Text `json:"address"`
	GstNumber         pgtype.Text `json:"gst_number"`
	Remarks           pgtype.Text `json:"remarks"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.Exec(ctx, createTenant,
		arg.TenantUuid,
		arg.TenantCode,
		arg.TenantID,
		arg.TenantName,
		arg.EmailAddress,
		arg.ContactPersonName,
		arg.MobileNumber,
		arg.CountryName,
		arg.StateName,
		arg.CityName,
		arg.Address,
		arg.GstNumber,
		arg.Remarks,
	)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
UPDATE tenant
SET tenant_status_universal_uuid = (
    SELECT universal_uuid FROM mst_universal 
    WHERE value_name = 'Inactive' 
    LIMIT 1
), updated_at = now()
WHERE tenant.tenant_uuid = $1 AND tenant.is_deleted = false
`

func (q *Queries) DeleteTenant(ctx context.Context, tenantUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, tenantUuid)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT 
    tenant_uuid, tenant_code, tenant_id, tenant_name, email_address,
    contact_person_name, mobile_number, country_name, state_name, city_name, address, gst_number, remarks,
    created_at, updated_at
FROM tenant
WHERE tenant_uuid = $1 AND is_deleted = false
`

type GetTenantByIDRow struct {
	TenantUuid        pgtype.UUID        `json:"tenant_uuid"`
	TenantCode        string             `json:"tenant_code"`
	TenantID          string             `json:"tenant_id"`
	TenantName        string             `json:"tenant_name"`
	EmailAddress      pgtype.Text        `json:"email_address"`
	ContactPersonName pgtype.Text        `json:"contact_person_name"`
	MobileNumber      pgtype.Text        `json:"mobile_number"`
	CountryName       pgtype.Text        `json:"country_name"`
	StateName         pgtype.Text        `json:"state_name"`
	CityName          pgtype.Text        `json:"city_name"`
	Address           pgtype.Text        `json:"address"`
	GstNumber         pgtype.Text        `json:"gst_number"`
	Remarks           pgtype.Text        `json:"remarks"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTenantByID(ctx context.Context, tenantUuid pgtype.UUID) (GetTenantByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantByID, tenantUuid)
	var i GetTenantByIDRow
	err := row.Scan(
		&i.TenantUuid,
		&i.TenantCode,
		&i.TenantID,
		&i.TenantName,
		&i.EmailAddress,
		&i.ContactPersonName,
		&i.MobileNumber,
		&i.CountryName,
		&i.StateName,
		&i.CityName,
		&i.Address,
		&i.GstNumber,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantStats = `-- name: GetTenantStats :one
SELECT 
    COUNT(*) AS total_customers,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Active') AS active_customers,
    COUNT(*) FILTER (WHERE u_status.value_name = 'Trial') AS trial_customers,
    COUNT(*) FILTER (WHERE u_status.value_name IN ('Inactive', 'Suspended')) AS inactive_customers,
    COALESCE(SUM(pp.price_amount) FILTER (WHERE u_status.value_name = 'Active'), 0) AS total_mrr
FROM tenant t
LEFT OUTER JOIN mst_universal u_status ON t.tenant_status_universal_uuid = u_status.universal_uuid
LEFT OUTER JOIN tenant_subscription ts ON t.tenant_uuid = ts.tenant_uuid AND ts.is_deleted = false
LEFT OUTER JOIN mst_plan_price pp ON ts.plan_price_uuid = pp.plan_price_uuid
WHERE t.is_deleted = false
`

type GetTenantStatsRow struct {
	TotalCustomers    int64       `json:"total_customers"`
	ActiveCustomers   int64       `json:"active_customers"`
	TrialCustomers    int64       `json:"trial_customers"`
	InactiveCustomers int64       `json:"inactive_customers"`
	TotalMrr          interface{} `json:"total_mrr"`
}

func (q *Queries) GetTenantStats(ctx context.Context) (GetTenantStatsRow, error) {
	row := q.db.QueryRow(ctx, getTenantStats)
	var i GetTenantStatsRow
	err := row.Scan(
		&i.TotalCustomers,
		&i.ActiveCustomers,
		&i.TrialCustomers,
		&i.InactiveCustomers,
		&i.TotalMrr,
	)
	return i, err
}

const listTenantsPaginated = `-- name: ListTenantsPaginated :many
SELECT 
    t.tenant_uuid,
    t.tenant_name,
    t.email_address,
    COALESCE(u_status.value_name, 'Unknown') AS status,
    COALESCE(u_type.value_name, 'Unknown') AS plan_type,
    COALESCE(p.plan_name, 'None') AS plan,
    COALESCE(u_cycle.value_name, 'Monthly') AS billing_cycle,
    ts.subscription_start_date AS start_date,
    ts.subscription_end_date AS next_renewal,
    COALESCE(pp.price_amount, 0) AS mrr,
    COUNT(*) OVER() AS total_records
FROM tenant t
LEFT OUTER JOIN mst_universal u_status ON t.tenant_status_universal_uuid = u_status.universal_uuid
LEFT OUTER JOIN tenant_subscription ts ON t.tenant_uuid = ts.tenant_uuid AND ts.is_deleted = false
LEFT OUTER JOIN mst_plan_price pp ON ts.plan_price_uuid = pp.plan_price_uuid
LEFT OUTER JOIN mst_plan p ON pp.plan_uuid = p.plan_uuid
LEFT OUTER JOIN mst_universal u_type ON p.plan_type_universal_uuid = u_type.universal_uuid
LEFT OUTER JOIN mst_universal u_cycle ON pp.billing_cycle_universal_uuid = u_cycle.universal_uuid
WHERE 
    t.is_deleted = false
    AND ($1::text = '' OR t.tenant_name ILIKE '%' || $1 || '%' OR t.email_address ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR u_status.value_name = $2)
    AND ($3::text = '' OR u_type.value_name = $3)
    AND ($4::text = '' OR p.plan_name = $4)
    AND ($5::text = '' OR u_cycle.value_name = $5)
ORDER BY t.created_at DESC
LIMIT $7 OFFSET $6
`

type ListTenantsPaginatedParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Column5 string `json:"column_5"`
	Offset  int32  `json:"offset"`
	Limit   int32  `json:"limit"`
}

type ListTenantsPaginatedRow struct {
	TenantUuid   pgtype.UUID    `json:"tenant_uuid"`
	TenantName   string         `json:"tenant_name"`
	EmailAddress pgtype.Text    `json:"email_address"`
	Status       string         `json:"status"`
	PlanType     string         `json:"plan_type"`
	Plan         string         `json:"plan"`
	BillingCycle string         `json:"billing_cycle"`
	StartDate    pgtype.Date    `json:"start_date"`
	NextRenewal  pgtype.Date    `json:"next_renewal"`
	Mrr          pgtype.Numeric `json:"mrr"`
	TotalRecords int64          `json:"total_records"`
}

func (q *Queries) ListTenantsPaginated(ctx context.Context, arg ListTenantsPaginatedParams) ([]ListTenantsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listTenantsPaginated,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantsPaginatedRow
	for rows.Next() {
		var i ListTenantsPaginatedRow
		if err := rows.Scan(
			&i.TenantUuid,
			&i.TenantName,
			&i.EmailAddress,
			&i.Status,
			&i.PlanType,
			&i.Plan,
			&i.BillingCycle,
			&i.StartDate,
			&i.NextRenewal,
			&i.Mrr,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :exec
UPDATE tenant
SET tenant_name = $2, email_address = $3, updated_at = now()
WHERE tenant_uuid = $1 AND is_deleted = false
`

type UpdateTenantParams struct {
	TenantUuid   pgtype.UUID `json:"tenant_uuid"`
	TenantName   string      `json:"tenant_name"`
	EmailAddress pgtype.Text `json:"email_address"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) error {
	_, err := q.db.Exec(ctx, updateTenant, arg.TenantUuid, arg.TenantName, arg.EmailAddress)
	return err
}
