// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: universal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUniversal = `-- name: CreateUniversal :one
INSERT INTO mst_universal (
    universal_uuid,
    master_type_uuid,
    value_name,
    display_order,
    is_system,
    remarks,
    created_at,
    created_by_user_uuid,
    updated_at,
    updated_by_user_uuid
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $7, $8
) RETURNING universal_uuid, tenant_uuid, master_type_uuid, parent_universal_uuid, value_name, display_order, is_system, remarks, created_at, created_by_user_uuid, updated_at, updated_by_user_uuid, is_archived, archived_at, archived_by_user_uuid, is_deleted, deleted_at, deleted_by_user_uuid
`

type CreateUniversalParams struct {
	UniversalUuid     pgtype.UUID        `json:"universal_uuid"`
	MasterTypeUuid    pgtype.UUID        `json:"master_type_uuid"`
	ValueName         string             `json:"value_name"`
	DisplayOrder      int32              `json:"display_order"`
	IsSystem          bool               `json:"is_system"`
	Remarks           pgtype.Text        `json:"remarks"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedByUserUuid pgtype.UUID        `json:"created_by_user_uuid"`
}

func (q *Queries) CreateUniversal(ctx context.Context, arg CreateUniversalParams) (MstUniversal, error) {
	row := q.db.QueryRow(ctx, createUniversal,
		arg.UniversalUuid,
		arg.MasterTypeUuid,
		arg.ValueName,
		arg.DisplayOrder,
		arg.IsSystem,
		arg.Remarks,
		arg.CreatedAt,
		arg.CreatedByUserUuid,
	)
	var i MstUniversal
	err := row.Scan(
		&i.UniversalUuid,
		&i.TenantUuid,
		&i.MasterTypeUuid,
		&i.ParentUniversalUuid,
		&i.ValueName,
		&i.DisplayOrder,
		&i.IsSystem,
		&i.Remarks,
		&i.CreatedAt,
		&i.CreatedByUserUuid,
		&i.UpdatedAt,
		&i.UpdatedByUserUuid,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ArchivedByUserUuid,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedByUserUuid,
	)
	return i, err
}

const deactivateUniversal = `-- name: DeactivateUniversal :exec
UPDATE mst_universal SET is_deleted = true, updated_at = NOW() WHERE universal_uuid = $1
`

func (q *Queries) DeactivateUniversal(ctx context.Context, universalUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUniversal, universalUuid)
	return err
}

const getUniversalsByMasterType = `-- name: GetUniversalsByMasterType :many
SELECT universal_uuid, tenant_uuid, master_type_uuid, parent_universal_uuid, value_name, display_order, is_system, remarks, created_at, created_by_user_uuid, updated_at, updated_by_user_uuid, is_archived, archived_at, archived_by_user_uuid, is_deleted, deleted_at, deleted_by_user_uuid FROM mst_universal
WHERE master_type_uuid = $1
ORDER BY display_order ASC
`

func (q *Queries) GetUniversalsByMasterType(ctx context.Context, masterTypeUuid pgtype.UUID) ([]MstUniversal, error) {
	rows, err := q.db.Query(ctx, getUniversalsByMasterType, masterTypeUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MstUniversal
	for rows.Next() {
		var i MstUniversal
		if err := rows.Scan(
			&i.UniversalUuid,
			&i.TenantUuid,
			&i.MasterTypeUuid,
			&i.ParentUniversalUuid,
			&i.ValueName,
			&i.DisplayOrder,
			&i.IsSystem,
			&i.Remarks,
			&i.CreatedAt,
			&i.CreatedByUserUuid,
			&i.UpdatedAt,
			&i.UpdatedByUserUuid,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ArchivedByUserUuid,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.DeletedByUserUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUniversal = `-- name: UpdateUniversal :exec
UPDATE mst_universal SET value_name = $1, remarks = $2, updated_at = NOW() WHERE universal_uuid = $3
`

type UpdateUniversalParams struct {
	ValueName     string      `json:"value_name"`
	Remarks       pgtype.Text `json:"remarks"`
	UniversalUuid pgtype.UUID `json:"universal_uuid"`
}

func (q *Queries) UpdateUniversal(ctx context.Context, arg UpdateUniversalParams) error {
	_, err := q.db.Exec(ctx, updateUniversal, arg.ValueName, arg.Remarks, arg.UniversalUuid)
	return err
}
