// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"
)

const getUsageStats = `-- name: GetUsageStats :one
SELECT 
    (SELECT count(*) FROM tenant_subscription)::int AS active_subscriptions,
    (SELECT count(*) FROM "user")::int AS total_users,
    (SELECT COALESCE(sum(file_size), 0) FROM media)::bigint AS total_storage_bytes,
    (SELECT count(*) FROM message_log)::int AS total_messages_used
`

type GetUsageStatsRow struct {
	ActiveSubscriptions int32 `json:"active_subscriptions"`
	TotalUsers          int32 `json:"total_users"`
	TotalStorageBytes   int64 `json:"total_storage_bytes"`
	TotalMessagesUsed   int32 `json:"total_messages_used"`
}

func (q *Queries) GetUsageStats(ctx context.Context) (GetUsageStatsRow, error) {
	row := q.db.QueryRow(ctx, getUsageStats)
	var i GetUsageStatsRow
	err := row.Scan(
		&i.ActiveSubscriptions,
		&i.TotalUsers,
		&i.TotalStorageBytes,
		&i.TotalMessagesUsed,
	)
	return i, err
}
